<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AGNtC43Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aGNtC43' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aGNtC43'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gateway' => ['privates', '.errored..service_locator.aGNtC43.Payum\\Core\\GatewayInterface', NULL, 'Cannot autowire service ".service_locator.aGNtC43": it references interface "Payum\\Core\\GatewayInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'gateway' => 'Payum\\Core\\GatewayInterface',
        ]);
    }
}
