<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_HaiO5dFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.haiO5dF' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        $a = ($container->privates['messenger.redispatch_message_handler'] ?? $container->load('getMessenger_RedispatchMessageHandlerService'));

        if (isset($container->privates['.messenger.handler_descriptor.haiO5dF'])) {
            return $container->privates['.messenger.handler_descriptor.haiO5dF'];
        }

        return $container->privates['.messenger.handler_descriptor.haiO5dF'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a, []);
    }
}
