<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_18HCDuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.18HC_Du' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        $a = ($container->services['Sylius\\RefundPlugin\\Listener\\UnitRefundedEventListener'] ?? $container->load('getUnitRefundedEventListenerService'));

        if (isset($container->privates['.messenger.handler_descriptor.18HC_Du'])) {
            return $container->privates['.messenger.handler_descriptor.18HC_Du'];
        }

        return $container->privates['.messenger.handler_descriptor.18HC_Du'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a, ['bus' => 'sylius.event_bus']);
    }
}
