<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VfPYPkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vf_PYPk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vf_PYPk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'PayPlug\\SyliusPayPlugPlugin\\Controller\\CompleteInfoController::__invoke' => ['privates', '.service_locator.rnIEV0M', 'get_ServiceLocator_RnIEV0MService', true],
            'PayPlug\\SyliusPayPlugPlugin\\Controller\\OneClickAction::setGateway' => ['privates', '.service_locator.aGNtC43', 'get_ServiceLocator_AGNtC43Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'PayPlug\\SyliusPayPlugPlugin\\Controller\\CompleteInfoController:__invoke' => ['privates', '.service_locator.rnIEV0M', 'get_ServiceLocator_RnIEV0MService', true],
            'PayPlug\\SyliusPayPlugPlugin\\Controller\\CompleteInfoController' => ['privates', '.service_locator.rnIEV0M', 'get_ServiceLocator_RnIEV0MService', true],
            'PayPlug\\SyliusPayPlugPlugin\\Controller\\OneClickAction:setGateway' => ['privates', '.service_locator.aGNtC43', 'get_ServiceLocator_AGNtC43Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'PayPlug\\SyliusPayPlugPlugin\\Controller\\CompleteInfoController::__invoke' => '?',
            'PayPlug\\SyliusPayPlugPlugin\\Controller\\OneClickAction::setGateway' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'PayPlug\\SyliusPayPlugPlugin\\Controller\\CompleteInfoController:__invoke' => '?',
            'PayPlug\\SyliusPayPlugPlugin\\Controller\\CompleteInfoController' => '?',
            'PayPlug\\SyliusPayPlugPlugin\\Controller\\OneClickAction:setGateway' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
