<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_L8USG1hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.L8USG1h' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        $a = ($container->services['Sylius\\RefundPlugin\\ProcessManager\\UnitsRefundedProcessManagerInterface'] ?? $container->load('getUnitsRefundedProcessManagerInterfaceService'));

        if (isset($container->privates['.messenger.handler_descriptor.L8USG1h'])) {
            return $container->privates['.messenger.handler_descriptor.L8USG1h'];
        }

        return $container->privates['.messenger.handler_descriptor.L8USG1h'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a, ['bus' => 'sylius.event_bus']);
    }
}
