<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreatePayPalOrderActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\CreatePayPalOrderAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\CreatePayPalOrderAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/CreatePayPalOrderAction.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\CreatePayPalOrderAction'] = new \Sylius\PayPalPlugin\Controller\CreatePayPalOrderAction(NULL, NULL, NULL, NULL, ($container->privates['Sylius\\PayPalPlugin\\Manager\\PaymentStateManagerInterface'] ?? $container->load('getPaymentStateManagerInterfaceService')), ($container->privates['Sylius\\PayPalPlugin\\Provider\\OrderProviderInterface'] ?? $container->load('getOrderProviderInterfaceService')), ($container->privates['Sylius\\PayPalPlugin\\Resolver\\CapturePaymentResolverInterface'] ?? $container->load('getCapturePaymentResolverInterfaceService')));
    }
}
