<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditMemoRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\RefundPlugin\Doctrine\ORM\CreditMemoRepository' shared service.
     *
     * @return \Sylius\RefundPlugin\Doctrine\ORM\CreditMemoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Repository/CreditMemoRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Doctrine/ORM/CreditMemoRepository.php';

        return $container->privates['Sylius\\RefundPlugin\\Doctrine\\ORM\\CreditMemoRepository'] = $container->get('sylius_refund.repository.credit_memo');
    }
}
