<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountOrderItemUnitRefundsBelongingToOrderQueryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Doctrine\ORM\CountOrderItemUnitRefundsBelongingToOrderQuery' shared service.
     *
     * @return \Sylius\RefundPlugin\Doctrine\ORM\CountOrderItemUnitRefundsBelongingToOrderQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Doctrine/ORM/CountRefundsBelongingToOrderQueryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Doctrine/ORM/CountOrderItemUnitRefundsBelongingToOrderQuery.php';

        return $container->services['Sylius\\RefundPlugin\\Doctrine\\ORM\\CountOrderItemUnitRefundsBelongingToOrderQuery'] = new \Sylius\RefundPlugin\Doctrine\ORM\CountOrderItemUnitRefundsBelongingToOrderQuery(($container->services['sylius.repository.order_item_unit'] ?? self::getSylius_Repository_OrderItemUnitService($container)));
    }
}
