<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerResolverInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\CoreBundle\Resolver\CustomerResolverInterface' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Resolver\CustomerResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resolver/CustomerResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resolver/CustomerResolver.php';

        return $container->services['Sylius\\Bundle\\CoreBundle\\Resolver\\CustomerResolverInterface'] = new \Sylius\Bundle\CoreBundle\Resolver\CustomerResolver(($container->services['sylius.factory.customer'] ??= new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Customer\\Customer')), ($container->services['Sylius\\Bundle\\CoreBundle\\Provider\\CustomerProviderInterface'] ?? $container->load('getCustomerProviderInterfaceService')));
    }
}
