<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompleteRefundPaymentAction2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Action\CompleteRefundPaymentAction' shared service.
     *
     * @return \Sylius\RefundPlugin\Action\CompleteRefundPaymentAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Action/CompleteRefundPaymentAction.php';

        return $container->services['Sylius\\RefundPlugin\\Action\\CompleteRefundPaymentAction'] = new \Sylius\RefundPlugin\Action\CompleteRefundPaymentAction(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['sylius_refund.repository.refund_payment'] ?? self::getSyliusRefund_Repository_RefundPaymentService($container)), ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['Sylius\\RefundPlugin\\StateResolver\\RefundPaymentCompletedStateApplierInterface'] ?? $container->load('getRefundPaymentCompletedStateApplierInterfaceService')), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
