<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditMemoFileResolverInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Resolver\CreditMemoFileResolverInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Resolver\CreditMemoFileResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Resolver/CreditMemoFileResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Resolver/CreditMemoFileResolver.php';

        return $container->services['Sylius\\RefundPlugin\\Resolver\\CreditMemoFileResolverInterface'] = new \Sylius\RefundPlugin\Resolver\CreditMemoFileResolver(($container->services['sylius_refund.repository.credit_memo'] ?? $container->load('getSyliusRefund_Repository_CreditMemoService')), ($container->services['Sylius\\RefundPlugin\\Provider\\CreditMemoFileProviderInterface'] ?? $container->load('getCreditMemoFileProviderInterfaceService')), ($container->services['Sylius\\RefundPlugin\\Generator\\CreditMemoPdfFileGeneratorInterface'] ?? $container->load('getCreditMemoPdfFileGeneratorInterfaceService')), ($container->services['Sylius\\RefundPlugin\\Manager\\CreditMemoFileManagerInterface'] ?? $container->load('getCreditMemoFileManagerInterfaceService')));
    }
}
