<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditMemoIdentifierGeneratorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Generator\CreditMemoIdentifierGeneratorInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Generator\UuidCreditMemoIdentifierGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Generator/CreditMemoIdentifierGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Generator/UuidCreditMemoIdentifierGenerator.php';

        return $container->services['Sylius\\RefundPlugin\\Generator\\CreditMemoIdentifierGeneratorInterface'] = new \Sylius\RefundPlugin\Generator\UuidCreditMemoIdentifierGenerator();
    }
}
