<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditMemoFileResponseBuilderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\ResponseBuilder\CreditMemoFileResponseBuilderInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\ResponseBuilder\CreditMemoFileResponseBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/ResponseBuilder/CreditMemoFileResponseBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/ResponseBuilder/CreditMemoFileResponseBuilder.php';

        return $container->services['Sylius\\RefundPlugin\\ResponseBuilder\\CreditMemoFileResponseBuilderInterface'] = new \Sylius\RefundPlugin\ResponseBuilder\CreditMemoFileResponseBuilder();
    }
}
