<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountShipmentRefundsBelongingToOrderQueryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Doctrine\ORM\CountShipmentRefundsBelongingToOrderQuery' shared service.
     *
     * @return \Sylius\RefundPlugin\Doctrine\ORM\CountShipmentRefundsBelongingToOrderQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Doctrine/ORM/CountRefundsBelongingToOrderQueryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Doctrine/ORM/CountShipmentRefundsBelongingToOrderQuery.php';

        return $container->services['Sylius\\RefundPlugin\\Doctrine\\ORM\\CountShipmentRefundsBelongingToOrderQuery'] = new \Sylius\RefundPlugin\Doctrine\ORM\CountShipmentRefundsBelongingToOrderQuery(($container->services['sylius.repository.adjustment'] ?? $container->load('getSylius_Repository_AdjustmentService')));
    }
}
