<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditMemoProcessManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\ProcessManager\CreditMemoProcessManager' shared service.
     *
     * @return \Sylius\RefundPlugin\ProcessManager\CreditMemoProcessManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/ProcessManager/UnitsRefundedProcessStepInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/ProcessManager/CreditMemoProcessManager.php';

        $a = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->services['Sylius\\RefundPlugin\\ProcessManager\\CreditMemoProcessManager'])) {
            return $container->services['Sylius\\RefundPlugin\\ProcessManager\\CreditMemoProcessManager'];
        }

        return $container->services['Sylius\\RefundPlugin\\ProcessManager\\CreditMemoProcessManager'] = new \Sylius\RefundPlugin\ProcessManager\CreditMemoProcessManager($a);
    }
}
