<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompleteInfoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'PayPlug\SyliusPayPlugPlugin\Controller\CompleteInfoController' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Controller\CompleteInfoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Controller/CompleteInfoController.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Validator/OneyInvalidDataRetriever.php';

        $container->services['PayPlug\\SyliusPayPlugPlugin\\Controller\\CompleteInfoController'] = $instance = new \PayPlug\SyliusPayPlugPlugin\Controller\CompleteInfoController(($container->privates['PayPlug\\SyliusPayPlugPlugin\\Validator\\OneyInvalidDataRetriever'] ??= new \PayPlug\SyliusPayPlugPlugin\Validator\OneyInvalidDataRetriever()), ($container->services['sylius.repository.customer'] ?? $container->load('getSylius_Repository_CustomerService')), ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)));

        $instance->setContainer(($container->privates['.service_locator.lhzYNGm'] ?? $container->load('get_ServiceLocator_LhzYNGmService'))->withContext('PayPlug\\SyliusPayPlugPlugin\\Controller\\CompleteInfoController', $container));

        return $instance;
    }
}
