<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'PayPlug\SyliusPayPlugPlugin\Controller\CardController' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Controller\CardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Controller/CardController.php';

        $container->services['PayPlug\\SyliusPayPlugPlugin\\Controller\\CardController'] = $instance = new \PayPlug\SyliusPayPlugPlugin\Controller\CardController(($container->services['sylius.context.customer'] ?? self::getSylius_Context_CustomerService($container)), ($container->services['payplug.repository.payplug_card'] ?? $container->load('getPayplug_Repository_PayplugCardService')), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['payplug_sylius_payplug_plugin.api_client.payplug'] ?? $container->load('getPayplugSyliusPayplugPlugin_ApiClient_PayplugService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['doctrine'] ?? self::getDoctrineService($container)));

        $instance->setContainer(($container->privates['.service_locator.lhzYNGm'] ?? $container->load('get_ServiceLocator_LhzYNGmService'))->withContext('PayPlug\\SyliusPayPlugPlugin\\Controller\\CardController', $container));

        return $instance;
    }
}
