<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditMemoNumberGeneratorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Generator\CreditMemoNumberGeneratorInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Generator\SequentialCreditMemoNumberGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Generator/CreditMemoNumberGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Generator/SequentialCreditMemoNumberGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/CreditMemoSequenceFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/CreditMemoSequenceFactory.php';

        $a = ($container->services['sylius_refund_plugin.repository.credit_memo_sequence'] ?? $container->load('getSyliusRefundPlugin_Repository_CreditMemoSequenceService'));

        if (isset($container->services['Sylius\\RefundPlugin\\Generator\\CreditMemoNumberGeneratorInterface'])) {
            return $container->services['Sylius\\RefundPlugin\\Generator\\CreditMemoNumberGeneratorInterface'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Sylius\\RefundPlugin\\Generator\\CreditMemoNumberGeneratorInterface'])) {
            return $container->services['Sylius\\RefundPlugin\\Generator\\CreditMemoNumberGeneratorInterface'];
        }

        return $container->services['Sylius\\RefundPlugin\\Generator\\CreditMemoNumberGeneratorInterface'] = new \Sylius\RefundPlugin\Generator\SequentialCreditMemoNumberGenerator($a, ($container->services['Sylius\\RefundPlugin\\Factory\\CreditMemoSequenceFactoryInterface'] ??= new \Sylius\RefundPlugin\Factory\CreditMemoSequenceFactory()), $b);
    }
}
