<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditMemoFileManagerInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Manager\CreditMemoFileManagerInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Manager\CreditMemoFileManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Manager/CreditMemoFileManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Manager/CreditMemoFileManager.php';

        return $container->services['Sylius\\RefundPlugin\\Manager\\CreditMemoFileManagerInterface'] = new \Sylius\RefundPlugin\Manager\CreditMemoFileManager(($container->services['gaufrette.sylius_refund_credit_memo_filesystem'] ?? $container->load('getGaufrette_SyliusRefundCreditMemoFilesystemService')));
    }
}
