<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDownloadCreditMemoAction2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Action\Shop\DownloadCreditMemoAction' shared service.
     *
     * @return \Sylius\RefundPlugin\Action\Shop\DownloadCreditMemoAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Action/Shop/DownloadCreditMemoAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/ResponseBuilder/CreditMemoFileResponseBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/ResponseBuilder/CreditMemoFileResponseBuilder.php';

        return $container->services['Sylius\\RefundPlugin\\Action\\Shop\\DownloadCreditMemoAction'] = new \Sylius\RefundPlugin\Action\Shop\DownloadCreditMemoAction(($container->services['Sylius\\RefundPlugin\\Resolver\\CreditMemoFileResolverInterface'] ?? $container->load('getCreditMemoFileResolverInterfaceService')), ($container->services['Sylius\\RefundPlugin\\Checker\\CreditMemoCustomerRelationCheckerInterface'] ?? $container->load('getCreditMemoCustomerRelationCheckerInterfaceService')), ($container->services['Sylius\\RefundPlugin\\ResponseBuilder\\CreditMemoFileResponseBuilderInterface'] ??= new \Sylius\RefundPlugin\ResponseBuilder\CreditMemoFileResponseBuilder()), true);
    }
}
