<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIpnActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'PayPlug\SyliusPayPlugPlugin\Controller\IpnAction' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Controller\IpnAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Controller/IpnAction.php';

        return $container->services['PayPlug\\SyliusPayPlugPlugin\\Controller\\IpnAction'] = new \PayPlug\SyliusPayPlugPlugin\Controller\IpnAction(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->privates['PayPlug\\SyliusPayPlugPlugin\\Handler\\PaymentNotificationHandler'] ?? $container->load('getPaymentNotificationHandlerService')), ($container->privates['PayPlug\\SyliusPayPlugPlugin\\Handler\\RefundNotificationHandler'] ?? $container->load('getRefundNotificationHandlerService')), ($container->privates['PayPlug\\SyliusPayPlugPlugin\\ApiClient\\PayPlugApiClientFactoryInterface'] ?? $container->load('getPayPlugApiClientFactoryInterfaceService')), ($container->services['payplug_sylius_payplug_plugin.repository.payment'] ?? $container->load('getPayplugSyliusPayplugPlugin_Repository_PaymentService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
