<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntegratedPaymentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'PayPlug\SyliusPayPlugPlugin\Controller\IntegratedPaymentController' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Controller\IntegratedPaymentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Controller/IntegratedPaymentController.php';

        $container->services['PayPlug\\SyliusPayPlugPlugin\\Controller\\IntegratedPaymentController'] = $instance = new \PayPlug\SyliusPayPlugPlugin\Controller\IntegratedPaymentController(($container->services['sylius.context.cart'] ?? self::getSylius_Context_CartService($container)), ($container->services['sylius.repository.payment_method'] ?? self::getSylius_Repository_PaymentMethodService($container)), ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->privates['PayPlug\\SyliusPayPlugPlugin\\Creator\\PayPlugPaymentDataCreator'] ?? $container->load('getPayPlugPaymentDataCreatorService')), ($container->privates['PayPlug\\SyliusPayPlugPlugin\\ApiClient\\PayPlugApiClientFactory'] ?? self::getPayPlugApiClientFactoryService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.lhzYNGm'] ?? $container->load('get_ServiceLocator_LhzYNGmService'))->withContext('PayPlug\\SyliusPayPlugPlugin\\Controller\\IntegratedPaymentController', $container));

        return $instance;
    }
}
