<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_Twig_RuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'knp_menu.twig.runtime' shared service.
     *
     * @return \Knp\Menu\Twig\MenuRuntimeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Twig/MenuRuntimeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Twig/Helper.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Renderer/RendererProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Renderer/PsrProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Util/MenuManipulator.php';

        $a = ($container->privates['knp_menu.menu_provider.chain'] ?? $container->load('getKnpMenu_MenuProvider_ChainService'));

        if (isset($container->privates['knp_menu.twig.runtime'])) {
            return $container->privates['knp_menu.twig.runtime'];
        }
        $b = new \Knp\Menu\Util\MenuManipulator();
        $c = ($container->services['knp_menu.matcher'] ?? $container->load('getKnpMenu_MatcherService'));

        return $container->privates['knp_menu.twig.runtime'] = new \Knp\Menu\Twig\MenuRuntimeExtension(new \Knp\Menu\Twig\Helper(new \Knp\Menu\Renderer\PsrProvider(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'list' => ['privates', 'knp_menu.renderer.list', 'getKnpMenu_Renderer_ListService', true],
            'twig' => ['privates', 'knp_menu.renderer.twig', 'getKnpMenu_Renderer_TwigService', true],
        ], [
            'list' => '?',
            'twig' => '?',
        ]), 'twig', [], false), $a, $b, $c), $c, $b);
    }
}
