<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLineItemsConverterInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Converter\LineItem\LineItemsConverterInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Converter\LineItem\CompositeLineItemConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Converter/LineItem/LineItemsConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Converter/LineItem/CompositeLineItemConverter.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Filter/UnitRefundFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Filter/UnitRefundFilter.php';

        return $container->services['Sylius\\RefundPlugin\\Converter\\LineItem\\LineItemsConverterInterface'] = new \Sylius\RefundPlugin\Converter\LineItem\CompositeLineItemConverter(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['Sylius\\RefundPlugin\\Converter\\LineItem\\OrderItemUnitLineItemsConverter'] ?? $container->load('getOrderItemUnitLineItemsConverter2Service'));
            yield 1 => ($container->services['Sylius\\RefundPlugin\\Converter\\LineItem\\ShipmentLineItemsConverter'] ?? $container->load('getShipmentLineItemsConverter2Service'));
        }, 2), ($container->services['Sylius\\RefundPlugin\\Filter\\UnitRefundFilterInterface'] ??= new \Sylius\RefundPlugin\Filter\UnitRefundFilter()));
    }
}
