<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLineItemFactoryInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Factory\LineItemFactoryInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Factory\LineItemFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/LineItemFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/LineItemFactory.php';

        return $container->services['Sylius\\RefundPlugin\\Factory\\LineItemFactoryInterface'] = new \Sylius\RefundPlugin\Factory\LineItemFactory('Sylius\\RefundPlugin\\Entity\\LineItem');
    }
}
