<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOneySimulationPopinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'PayPlug\SyliusPayPlugPlugin\Controller\OneySimulationPopin' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Controller\OneySimulationPopin
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Controller/AbstractOneyController.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Controller/OneySimulationPopin.php';

        $container->services['PayPlug\\SyliusPayPlugPlugin\\Controller\\OneySimulationPopin'] = $instance = new \PayPlug\SyliusPayPlugPlugin\Controller\OneySimulationPopin(($container->privates['PayPlug\\SyliusPayPlugPlugin\\Provider\\OneySimulation\\CachedSimulationDataProvider'] ?? self::getCachedSimulationDataProviderService($container)), ($container->services['sylius.context.cart'] ?? self::getSylius_Context_CartService($container)), ($container->services['sylius.repository.product'] ?? self::getSylius_Repository_ProductService($container)), ($container->services['sylius.repository.product_variant'] ?? self::getSylius_Repository_ProductVariantService($container)), ($container->services['sylius.custom_factory.order'] ?? self::getSylius_CustomFactory_OrderService($container)), ($container->services['sylius.factory.cart_item'] ?? $container->load('getSylius_Factory_CartItemService')), ($container->services['sylius.order_modifier'] ?? $container->load('getSylius_OrderModifierService')), ($container->services['sylius.order_item_quantity_modifier.limiting'] ?? $container->load('getSylius_OrderItemQuantityModifier_LimitingService')), ($container->privates['PayPlug\\SyliusPayPlugPlugin\\Twig\\OneyRulesExtension'] ?? self::getOneyRulesExtensionService($container)));

        $instance->setContainer(($container->privates['.service_locator.lhzYNGm'] ?? $container->load('get_ServiceLocator_LhzYNGmService'))->withContext('PayPlug\\SyliusPayPlugPlugin\\Controller\\OneySimulationPopin', $container));

        return $instance;
    }
}
