<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderItemUnitLineItemsConverter2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Converter\LineItem\OrderItemUnitLineItemsConverter' shared service.
     *
     * @return \Sylius\RefundPlugin\Converter\LineItem\OrderItemUnitLineItemsConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Converter/LineItem/LineItemsConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Converter/LineItem/LineItemsConverterUnitRefundAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Converter/LineItem/OrderItemUnitLineItemsConverter.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/TaxRateProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/TaxRateProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/LineItemFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/LineItemFactory.php';

        return $container->services['Sylius\\RefundPlugin\\Converter\\LineItem\\OrderItemUnitLineItemsConverter'] = new \Sylius\RefundPlugin\Converter\LineItem\OrderItemUnitLineItemsConverter(($container->services['sylius.repository.order_item_unit'] ?? self::getSylius_Repository_OrderItemUnitService($container)), ($container->services['Sylius\\RefundPlugin\\Provider\\TaxRateProviderInterface'] ??= new \Sylius\RefundPlugin\Provider\TaxRateProvider()), ($container->services['Sylius\\RefundPlugin\\Factory\\LineItemFactoryInterface'] ??= new \Sylius\RefundPlugin\Factory\LineItemFactory('Sylius\\RefundPlugin\\Entity\\LineItem')));
    }
}
