<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderRefundingAvailabilityCheckerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Checker\OrderRefundingAvailabilityChecker' shared service.
     *
     * @return \Sylius\RefundPlugin\Checker\OrderRefundingAvailabilityChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Checker/OrderRefundingAvailabilityCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Checker/OrderRefundingAvailabilityChecker.php';

        return $container->services['Sylius\\RefundPlugin\\Checker\\OrderRefundingAvailabilityChecker'] = new \Sylius\RefundPlugin\Checker\OrderRefundingAvailabilityChecker(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)));
    }
}
