<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderItemUnitTotalProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Provider\OrderItemUnitTotalProvider' shared service.
     *
     * @return \Sylius\RefundPlugin\Provider\OrderItemUnitTotalProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/RefundUnitTotalProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/OrderItemUnitTotalProvider.php';

        return $container->services['Sylius\\RefundPlugin\\Provider\\OrderItemUnitTotalProvider'] = new \Sylius\RefundPlugin\Provider\OrderItemUnitTotalProvider(($container->services['sylius.repository.order_item_unit'] ?? self::getSylius_Repository_OrderItemUnitService($container)));
    }
}
