<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderPartiallyRefundedStateResolverInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\StateResolver\OrderPartiallyRefundedStateResolverInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\StateResolver\OrderPartiallyRefundedStateResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/StateResolver/OrderPartiallyRefundedStateResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/StateResolver/OrderPartiallyRefundedStateResolver.php';

        $a = ($container->services['SM\\Factory\\FactoryInterface'] ?? self::getFactoryInterfaceService($container));

        if (isset($container->services['Sylius\\RefundPlugin\\StateResolver\\OrderPartiallyRefundedStateResolverInterface'])) {
            return $container->services['Sylius\\RefundPlugin\\StateResolver\\OrderPartiallyRefundedStateResolverInterface'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Sylius\\RefundPlugin\\StateResolver\\OrderPartiallyRefundedStateResolverInterface'])) {
            return $container->services['Sylius\\RefundPlugin\\StateResolver\\OrderPartiallyRefundedStateResolverInterface'];
        }

        return $container->services['Sylius\\RefundPlugin\\StateResolver\\OrderPartiallyRefundedStateResolverInterface'] = new \Sylius\RefundPlugin\StateResolver\OrderPartiallyRefundedStateResolver(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), $a, $b);
    }
}
