<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderShowMenuListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Menu\OrderShowMenuListener' shared service.
     *
     * @return \Sylius\RefundPlugin\Menu\OrderShowMenuListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Menu/OrderShowMenuListener.php';

        return $container->services['Sylius\\RefundPlugin\\Menu\\OrderShowMenuListener'] = new \Sylius\RefundPlugin\Menu\OrderShowMenuListener(($container->services['Sylius\\RefundPlugin\\Checker\\OrderRefundsListAvailabilityChecker'] ?? $container->load('getOrderRefundsListAvailabilityCheckerService')));
    }
}
