<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderRefundsListActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Action\Admin\OrderRefundsListAction' shared service.
     *
     * @return \Sylius\RefundPlugin\Action\Admin\OrderRefundsListAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Action/Admin/OrderRefundsListAction.php';

        return $container->services['Sylius\\RefundPlugin\\Action\\Admin\\OrderRefundsListAction'] = new \Sylius\RefundPlugin\Action\Admin\OrderRefundsListAction(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['Sylius\\RefundPlugin\\Checker\\OrderRefundsListAvailabilityChecker'] ?? $container->load('getOrderRefundsListAvailabilityCheckerService')), ($container->services['Sylius\\RefundPlugin\\Provider\\RefundPaymentMethodsProviderInterface'] ?? $container->load('getRefundPaymentMethodsProviderInterfaceService')), ($container->services['twig'] ?? self::getTwigService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
