<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderItemUnitsRefunderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Refunder\OrderItemUnitsRefunder' shared service.
     *
     * @return \Sylius\RefundPlugin\Refunder\OrderItemUnitsRefunder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Refunder/RefunderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Refunder/OrderItemUnitsRefunder.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Filter/UnitRefundFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Filter/UnitRefundFilter.php';

        $a = ($container->services['Sylius\\RefundPlugin\\Creator\\RefundCreatorInterface'] ?? $container->load('getRefundCreatorInterfaceService'));

        if (isset($container->services['Sylius\\RefundPlugin\\Refunder\\OrderItemUnitsRefunder'])) {
            return $container->services['Sylius\\RefundPlugin\\Refunder\\OrderItemUnitsRefunder'];
        }
        $b = ($container->privates['debug.traced.sylius.event_bus'] ?? self::getDebug_Traced_Sylius_EventBusService($container));

        if (isset($container->services['Sylius\\RefundPlugin\\Refunder\\OrderItemUnitsRefunder'])) {
            return $container->services['Sylius\\RefundPlugin\\Refunder\\OrderItemUnitsRefunder'];
        }

        return $container->services['Sylius\\RefundPlugin\\Refunder\\OrderItemUnitsRefunder'] = new \Sylius\RefundPlugin\Refunder\OrderItemUnitsRefunder($a, $b, ($container->services['Sylius\\RefundPlugin\\Filter\\UnitRefundFilterInterface'] ??= new \Sylius\RefundPlugin\Filter\UnitRefundFilter()));
    }
}
