<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderFullyRefundedTotalCheckerInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Checker\OrderFullyRefundedTotalCheckerInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Checker\OrderFullyRefundedTotalChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Checker/OrderFullyRefundedTotalCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Checker/OrderFullyRefundedTotalChecker.php';

        return $container->services['Sylius\\RefundPlugin\\Checker\\OrderFullyRefundedTotalCheckerInterface'] = new \Sylius\RefundPlugin\Checker\OrderFullyRefundedTotalChecker(($container->services['Sylius\\RefundPlugin\\Provider\\OrderRefundedTotalProviderInterface'] ?? self::getOrderRefundedTotalProviderInterfaceService($container)));
    }
}
