<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplugSyliusPayplugPlugin_PaymentProcessing_AbortService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payplug_sylius_payplug_plugin.payment_processing.abort' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\PaymentProcessing\AbortPaymentProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/PaymentProcessing/AbortPaymentProcessor.php';

        return $container->services['payplug_sylius_payplug_plugin.payment_processing.abort'] = new \PayPlug\SyliusPayPlugPlugin\PaymentProcessing\AbortPaymentProcessor(($container->services['payplug_sylius_payplug_plugin.api_client.payplug'] ?? $container->load('getPayplugSyliusPayplugPlugin_ApiClient_PayplugService')));
    }
}
