<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplug_Repository_PayplugRefundHistoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payplug.repository.payplug_refund_history' shared service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Repository\RefundHistoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Repository/RefundHistoryRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Repository/RefundHistoryRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['payplug.repository.payplug_refund_history'])) {
            return $container->services['payplug.repository.payplug_refund_history'];
        }

        return $container->services['payplug.repository.payplug_refund_history'] = new \PayPlug\SyliusPayPlugPlugin\Repository\RefundHistoryRepository($a, $a->getClassMetadata('PayPlug\\SyliusPayPlugPlugin\\Entity\\RefundHistory'));
    }
}
