<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplugSyliusPayplugPlugin_IsCanSaveCardsValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'payplug_sylius_payplug_plugin.is_can_save_cards_validator' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Gateway\Validator\Constraints\IsCanSaveCardsValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Gateway/Validator/Constraints/IsCanSaveCardsValidator.php';

        $a = ($container->privates['PayPlug\\SyliusPayPlugPlugin\\ApiClient\\PayPlugApiClientFactory'] ?? self::getPayPlugApiClientFactoryService($container));

        if (isset($container->privates['payplug_sylius_payplug_plugin.is_can_save_cards_validator'])) {
            return $container->privates['payplug_sylius_payplug_plugin.is_can_save_cards_validator'];
        }

        return $container->privates['payplug_sylius_payplug_plugin.is_can_save_cards_validator'] = new \PayPlug\SyliusPayPlugPlugin\Gateway\Validator\Constraints\IsCanSaveCardsValidator($a);
    }
}
