<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplugSyliusPayplugPlugin_Repository_PaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payplug_sylius_payplug_plugin.repository.payment' shared service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Repository\PaymentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Repository/PaymentRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Repository/PaymentRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Repository/PaymentRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        return $container->services['payplug_sylius_payplug_plugin.repository.payment'] = new \PayPlug\SyliusPayPlugPlugin\Repository\PaymentRepository($a, $a->getClassMetadata('App\\Entity\\Payment\\Payment'));
    }
}
