<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplugSyliusPayplugPlugin_Action_NotifyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payplug_sylius_payplug_plugin.action.notify' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Action\NotifyAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Action/ActionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/ApiAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/GatewayAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/GatewayAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Action/Api/ApiAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Action/NotifyAction.php';

        return $container->services['payplug_sylius_payplug_plugin.action.notify'] = new \PayPlug\SyliusPayPlugPlugin\Action\NotifyAction(($container->privates['monolog.logger.payum'] ?? self::getMonolog_Logger_PayumService($container)), ($container->privates['PayPlug\\SyliusPayPlugPlugin\\Handler\\PaymentNotificationHandler'] ?? $container->load('getPaymentNotificationHandlerService')), ($container->privates['PayPlug\\SyliusPayPlugPlugin\\Handler\\RefundNotificationHandler'] ?? $container->load('getRefundNotificationHandlerService')));
    }
}
