<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentTypeExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'PayPlug\SyliusPayPlugPlugin\Form\Extension\PaymentTypeExtension' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Form\Extension\PaymentTypeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Form/Extension/PaymentTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Checker/OneyOrderChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Validator/OneyInvalidDataRetriever.php';

        return $container->privates['PayPlug\\SyliusPayPlugPlugin\\Form\\Extension\\PaymentTypeExtension'] = new \PayPlug\SyliusPayPlugPlugin\Form\Extension\PaymentTypeExtension(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['translator'] ?? self::getTranslatorService($container)), new \PayPlug\SyliusPayPlugPlugin\Checker\OneyOrderChecker(($container->privates['PayPlug\\SyliusPayPlugPlugin\\Validator\\OneyInvalidDataRetriever'] ??= new \PayPlug\SyliusPayPlugPlugin\Validator\OneyInvalidDataRetriever())), ($container->privates['PayPlug\\SyliusPayPlugPlugin\\Provider\\OneySupportedPaymentChoiceProvider'] ?? self::getOneySupportedPaymentChoiceProviderService($container)));
    }
}
