<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplugSyliusPayplugPlugin_Form_Type_PayplugGatewayConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'payplug_sylius_payplug_plugin.form.type.payplug_gateway_configuration' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Gateway\Form\Type\PayPlugGatewayConfigurationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Gateway/Form/Type/AbstractGatewayConfigurationType.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Gateway/Form/Type/PayPlugGatewayConfigurationType.php';

        return $container->privates['payplug_sylius_payplug_plugin.form.type.payplug_gateway_configuration'] = new \PayPlug\SyliusPayPlugPlugin\Gateway\Form\Type\PayPlugGatewayConfigurationType(($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['sylius.repository.gateway_config'] ?? self::getSylius_Repository_GatewayConfigService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
