<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplug_Factory_PayplugRefundHistoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payplug.factory.payplug_refund_history' shared service.
     *
     * @return \Sylius\Resource\Factory\Factory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['payplug.factory.payplug_refund_history'] = new \Sylius\Resource\Factory\Factory('PayPlug\\SyliusPayPlugPlugin\\Entity\\RefundHistory');
    }
}
