<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentNotificationHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'PayPlug\SyliusPayPlugPlugin\Handler\PaymentNotificationHandler' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Handler\PaymentNotificationHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Handler/PaymentNotificationHandler.php';

        return $container->privates['PayPlug\\SyliusPayPlugPlugin\\Handler\\PaymentNotificationHandler'] = new \PayPlug\SyliusPayPlugPlugin\Handler\PaymentNotificationHandler(($container->privates['monolog.logger.payum'] ?? self::getMonolog_Logger_PayumService($container)), ($container->services['payplug.repository.payplug_card'] ?? $container->load('getPayplug_Repository_PayplugCardService')), ($container->services['payplug.factory.payplug_card'] ??= new \Sylius\Resource\Factory\Factory('PayPlug\\SyliusPayPlugPlugin\\Entity\\Card')), ($container->services['sylius.repository.customer'] ?? $container->load('getSylius_Repository_CustomerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
