<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplugSyliusPayplugPlugin_PaymentProcessing_RefundHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payplug_sylius_payplug_plugin.payment_processing.refund_handler' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\PaymentProcessing\RefundPaymentHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/PaymentProcessing/RefundPaymentHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/PaymentProcessing/RefundPaymentHandler.php';

        return $container->services['payplug_sylius_payplug_plugin.payment_processing.refund_handler'] = new \PayPlug\SyliusPayPlugPlugin\PaymentProcessing\RefundPaymentHandler(($container->services['Sylius\\RefundPlugin\\Calculator\\UnitRefundTotalCalculatorInterface'] ?? $container->load('getUnitRefundTotalCalculatorInterfaceService')), ($container->services['Sylius\\RefundPlugin\\Provider\\RemainingTotalProviderInterface'] ?? self::getRemainingTotalProviderInterfaceService($container)), ($container->services['sylius_refund.repository.refund_payment'] ?? self::getSyliusRefund_Repository_RefundPaymentService($container)), ($container->services['Sylius\\RefundPlugin\\StateResolver\\RefundPaymentCompletedStateApplierInterface'] ?? $container->load('getRefundPaymentCompletedStateApplierInterfaceService')));
    }
}
