<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplugSyliusPayplugPlugin_IsPayplugSecretKeyValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'payplug_sylius_payplug_plugin.is_payplug_secret_key_validator' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Gateway\Validator\Constraints\IsPayPlugSecretKeyValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Gateway/Validator/Constraints/IsPayPlugSecretKeyValidator.php';

        return $container->privates['payplug_sylius_payplug_plugin.is_payplug_secret_key_validator'] = new \PayPlug\SyliusPayPlugPlugin\Gateway\Validator\Constraints\IsPayPlugSecretKeyValidator(($container->privates['PayPlug\\SyliusPayPlugPlugin\\ApiClient\\PayPlugApiClientFactory'] ?? self::getPayPlugApiClientFactoryService($container)));
    }
}
