<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayum_BuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'payum.builder' shared service.
     *
     * @return \Payum\Core\PayumBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/PayumBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum-bundle/Builder/HttpRequestVerifierBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum-bundle/Builder/TokenFactoryBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum-bundle/Builder/CoreGatewayFactoryBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Bridge/Symfony/Builder/GatewayFactoryBuilder.php';

        $container->privates['payum.builder'] = $instance = new \Payum\Core\PayumBuilder();

        $instance->setMainRegistry(($container->services['payum.static_registry'] ?? $container->load('getPayum_StaticRegistryService')));
        $instance->setHttpRequestVerifier(new \Payum\Bundle\PayumBundle\Builder\HttpRequestVerifierBuilder());
        $instance->setTokenFactory(new \Payum\Bundle\PayumBundle\Builder\TokenFactoryBuilder(($container->services['router'] ?? self::getRouterService($container))));
        $instance->setTokenStorage(($container->services['payum.security.token_storage'] ?? $container->load('getPayum_Security_TokenStorageService')));
        $instance->setGenericTokenFactoryPaths(['capture' => 'payum_capture_do', 'notify' => 'payum_notify_do', 'authorize' => 'payum_authorize_do', 'refund' => 'payum_refund_do', 'cancel' => 'payum_cancel_do', 'payout' => 'payum_payout_do']);
        $instance->setCoreGatewayFactory(new \Payum\Bundle\PayumBundle\Builder\CoreGatewayFactoryBuilder($container));
        $instance->addCoreGatewayFactoryConfig(['payum.template.layout' => '@PayumCore\\layout.html.twig', 'payum.template.obtain_credit_card' => '@PayumSymfonyBridge\\obtainCreditCard.html.twig', 'payum.paths' => ['PayumSymfonyBridge' => (\dirname(__DIR__, 4).'/vendor/payum/payum-bundle/Resources/views')], 'payum.action.get_http_request' => ($container->services['payum.action.get_http_request'] ?? $container->load('getPayum_Action_GetHttpRequestService')), 'payum.action.obtain_credit_card' => ($container->services['payum.action.obtain_credit_card_builder'] ?? $container->load('getPayum_Action_ObtainCreditCardBuilderService'))]);
        $instance->addGateway('offline', ['factory' => 'offline']);
        $instance->setGatewayConfigStorage(($container->services['payum.dynamic_gateways.config_storage'] ?? $container->load('getPayum_DynamicGateways_ConfigStorageService')));
        $instance->addCoreGatewayFactoryConfig(['twig.env' => ($container->services['twig'] ?? self::getTwigService($container))]);
        $instance->addCoreGatewayFactoryConfig(['payum.action.sylius.authorize_payment' => '@sylius.payum_action.authorize_payment', 'payum.action.sylius.capture_payment' => '@sylius.payum_action.capture_payment', 'payum.action.sylius.payum_action.execute_same_request_with_payment_details' => '@sylius.payum_action.execute_same_request_with_payment_details', 'payum.action.sylius.resolve_next_route' => '@sylius.payum_action.resolve_next_route', 'payum.extension.psr_logger' => '@payum.extension.logger', 'payum.extension.log_executed_actions' => '@payum.extension.log_executed_actions', 'payum.extension.profile_collector' => '@payum.profiler.payum_collector', 'payum.prepend_extensions' => ['payum.extension.profile_collector', 'payum.extension.sylius.payum_extension.update_payment_state'], 'payum.extension.payum.extension.storage.app_entity_order_order' => '@payum.extension.storage.app_entity_order_order', 'payum.extension.payum.extension.storage.app_entity_payment_payment' => '@payum.extension.storage.app_entity_payment_payment', 'payum.extension.sylius.payum_extension.update_payment_state' => '@sylius.payum_extension.update_payment_state']);
        $instance->addGatewayFactoryConfig('payplug', ['payum.action.payum.action.capture' => '@payplug_sylius_payplug_plugin.action.capture', 'payum.action.payum.action.status' => '@payplug_sylius_payplug_plugin.action.status', 'payum.action.payum.action.convert_payment' => '@payplug_sylius_payplug_plugin.action.convert_payment', 'payum.action.payum.action.notify' => '@payplug_sylius_payplug_plugin.action.notify']);
        $instance->addGatewayFactoryConfig('payplug_oney', ['payum.action.payum.action.capture' => '@payplug_sylius_payplug_plugin.action.capture', 'payum.action.payum.action.status' => '@payplug_sylius_payplug_plugin.action.status', 'payum.action.payum.action.convert_payment' => '@payplug_sylius_payplug_plugin.action.convert_payment', 'payum.action.payum.action.notify' => '@payplug_sylius_payplug_plugin.action.notify']);
        $instance->addGatewayFactoryConfig('payplug_bancontact', ['payum.action.payum.action.capture' => '@payplug_sylius_payplug_plugin.action.capture', 'payum.action.payum.action.status' => '@payplug_sylius_payplug_plugin.action.status', 'payum.action.payum.action.convert_payment' => '@payplug_sylius_payplug_plugin.action.convert_payment', 'payum.action.payum.action.notify' => '@payplug_sylius_payplug_plugin.action.notify']);
        $instance->addGatewayFactoryConfig('payplug_american_express', ['payum.action.payum.action.capture' => '@payplug_sylius_payplug_plugin.action.capture', 'payum.action.payum.action.status' => '@payplug_sylius_payplug_plugin.action.status', 'payum.action.payum.action.convert_payment' => '@payplug_sylius_payplug_plugin.action.convert_payment', 'payum.action.payum.action.notify' => '@payplug_sylius_payplug_plugin.action.notify']);
        $instance->addGatewayFactoryConfig('paypal_express_checkout', ['payum.action.sylius.paypal_express_checkout.convert_payment' => '@sylius.payum_action.paypal_express_checkout.convert_payment']);
        $instance->addGatewayFactoryConfig('offline', ['payum.action.sylius.offline.convert_payment' => '@sylius.payum_action.offline.convert_payment', 'payum.action.sylius.offline.status' => '@sylius.payum_action.offline.status', 'payum.action.sylius.offline.resolve_next_route' => '@sylius.payum_action.offline.resolve_next_route']);
        $instance->addGatewayFactoryConfig('sylius.pay_pal', ['payum.action.payum.action.authorize' => '@Sylius\\PayPalPlugin\\Payum\\Action\\AuthorizeAction', 'payum.action.payum.action.capture' => '@Sylius\\PayPalPlugin\\Payum\\Action\\CaptureAction', 'payum.action.payum.action.complete_order' => '@Sylius\\PayPalPlugin\\Payum\\Action\\CompleteOrderAction', 'payum.action.sylius.resolve_next_route' => '@Sylius\\PayPalPlugin\\Payum\\Action\\ResolveNextRouteAction']);
        $instance->addGatewayFactory('payplug', new \Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder('PayPlug\\SyliusPayPlugPlugin\\Gateway\\PayPlugGatewayFactory'));
        $instance->addGatewayFactory('payplug_oney', new \Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder('PayPlug\\SyliusPayPlugPlugin\\Gateway\\OneyGatewayFactory'));
        $instance->addGatewayFactory('payplug_bancontact', new \Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder('PayPlug\\SyliusPayPlugPlugin\\Gateway\\BancontactGatewayFactory'));
        $instance->addGatewayFactory('payplug_apple_pay', new \Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder('PayPlug\\SyliusPayPlugPlugin\\Gateway\\ApplePayGatewayFactory'));
        $instance->addGatewayFactory('payplug_american_express', new \Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder('PayPlug\\SyliusPayPlugPlugin\\Gateway\\AmericanExpressGatewayFactory'));
        $instance->addGatewayFactory('sylius.pay_pal', new \Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder('Sylius\\PayPalPlugin\\Payum\\Factory\\PayPalGatewayFactory'));

        return $instance;
    }
}
