<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplugSyliusPayplugPlugin_Form_TypeExtension_PayplugGatewayConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'payplug_sylius_payplug_plugin.form.type_extension.payplug_gateway_configuration' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Gateway\Form\Extension\PayPlugGatewayConfigurationTypeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Gateway/Form/Extension/PayPlugGatewayConfigurationTypeExtension.php';

        return $container->privates['payplug_sylius_payplug_plugin.form.type_extension.payplug_gateway_configuration'] = new \PayPlug\SyliusPayPlugPlugin\Gateway\Form\Extension\PayPlugGatewayConfigurationTypeExtension(($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
