<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalPaymentMethodNewResourceFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\Factory\PayPalPaymentMethodNewResourceFactory' shared service.
     *
     * @return \Sylius\PayPalPlugin\Factory\PayPalPaymentMethodNewResourceFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Controller/NewResourceFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Factory/PayPalPaymentMethodNewResourceFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Controller/NewResourceFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Onboarding/Processor/OnboardingProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Onboarding/Processor/BasicOnboardingProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/RequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ResponseFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ServerRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/StreamFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UploadedFileFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UriFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr17Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr18Client.php';

        return $container->privates['Sylius\\PayPalPlugin\\Factory\\PayPalPaymentMethodNewResourceFactory'] = new \Sylius\PayPalPlugin\Factory\PayPalPaymentMethodNewResourceFactory(new \Sylius\Bundle\ResourceBundle\Controller\NewResourceFactory(), new \Sylius\PayPalPlugin\Onboarding\Processor\BasicOnboardingProcessor(($container->privates['Http\\Discovery\\Psr18Client'] ??= new \Http\Discovery\Psr18Client()), ($container->privates['Sylius\\PayPalPlugin\\Registrar\\SellerWebhookRegistrarInterface'] ?? $container->load('getSellerWebhookRegistrarInterfaceService')), 'https://paypal.sylius.com', ($container->privates['http_discovery.psr17_factory'] ??= new \Http\Discovery\Psr17Factory())));
    }
}
