<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplug_ApplePayOrder_ProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payplug.apple_pay_order.provider' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Provider\ApplePayOrderProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Provider/ApplePayOrderProvider.php';

        return $container->services['payplug.apple_pay_order.provider'] = new \PayPlug\SyliusPayPlugPlugin\Provider\ApplePayOrderProvider(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
