<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplugSyliusPayplugPlugin_Action_StatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payplug_sylius_payplug_plugin.action.status' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Action\StatusAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Action/ActionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/GatewayAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/ApiAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/GatewayAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Action/Api/ApiAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Action/StatusAction.php';

        return $container->services['payplug_sylius_payplug_plugin.action.status'] = new \PayPlug\SyliusPayPlugPlugin\Action\StatusAction(($container->services['SM\\Factory\\FactoryInterface'] ?? self::getFactoryInterfaceService($container)), ($container->services['payplug_sylius_payplug_plugin.payment_processing.refund_handler'] ?? $container->load('getPayplugSyliusPayplugPlugin_PaymentProcessing_RefundHandlerService')), ($container->privates['PayPlug\\SyliusPayPlugPlugin\\Handler\\PaymentNotificationHandler'] ?? $container->load('getPaymentNotificationHandlerService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
