<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayplugSyliusPayplugPlugin_ApiClient_ApplePayService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payplug_sylius_payplug_plugin.api_client.apple_pay' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\ApiClient\PayPlugApiClient
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['payplug_sylius_payplug_plugin.api_client.apple_pay'] = $container->createProxy('PayPlugApiClientProxy54bbe73', static fn () => \PayPlugApiClientProxy54bbe73::createLazyProxy(static fn () => self::do($container, false)));
        }

        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/ApiClient/PayPlugApiClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/ApiClient/PayPlugApiClient.php';

        return ($container->privates['PayPlug\\SyliusPayPlugPlugin\\ApiClient\\PayPlugApiClientFactory'] ?? self::getPayPlugApiClientFactoryService($container))->create('payplug_apple_pay');
    }
}
