<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalPaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\ApiPlatform\PayPalPayment' shared service.
     *
     * @return \Sylius\PayPalPlugin\ApiPlatform\PayPalPayment
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/ApiPlatform/PayPalPayment.php';

        return $container->privates['Sylius\\PayPalPlugin\\ApiPlatform\\PayPalPayment'] = new \Sylius\PayPalPlugin\ApiPlatform\PayPalPayment(($container->services['router'] ?? self::getRouterService($container)), ($container->privates['Sylius\\PayPalPlugin\\Provider\\AvailableCountriesProviderInterface'] ?? $container->load('getAvailableCountriesProviderInterfaceService')));
    }
}
