<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPlugApiClientFactoryInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'PayPlug\SyliusPayPlugPlugin\ApiClient\PayPlugApiClientFactoryInterface' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\ApiClient\PayPlugApiClientFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PayPlug\\SyliusPayPlugPlugin\\ApiClient\\PayPlugApiClientFactoryInterface'] = new \PayPlug\SyliusPayPlugPlugin\ApiClient\PayPlugApiClientFactory(($container->services['sylius.repository.gateway_config'] ?? self::getSylius_Repository_GatewayConfigService($container)), ($container->services['cache.app'] ?? self::getCache_AppService($container)));
    }
}
