<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundUnitsAction2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Action\Admin\RefundUnitsAction' shared service.
     *
     * @return \Sylius\RefundPlugin\Action\Admin\RefundUnitsAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Action/Admin/RefundUnitsAction.php';

        return $container->services['Sylius\\RefundPlugin\\Action\\Admin\\RefundUnitsAction'] = new \Sylius\RefundPlugin\Action\Admin\RefundUnitsAction(($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['Sylius\\RefundPlugin\\Creator\\RequestCommandCreatorInterface'] ?? $container->load('getRequestCommandCreatorInterfaceService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['security.csrf.token_manager'] ?? $container->load('getSecurity_Csrf_TokenManagerService')));
    }
}
