<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestToOrderItemUnitRefundConverterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Converter\Request\RequestToOrderItemUnitRefundConverter' shared service.
     *
     * @return \Sylius\RefundPlugin\Converter\Request\RequestToOrderItemUnitRefundConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Converter/Request/RequestToRefundUnitsConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Converter/Request/RequestToOrderItemUnitRefundConverter.php';

        return $container->services['Sylius\\RefundPlugin\\Converter\\Request\\RequestToOrderItemUnitRefundConverter'] = new \Sylius\RefundPlugin\Converter\Request\RequestToOrderItemUnitRefundConverter(($container->services['Sylius\\RefundPlugin\\Converter\\RefundUnitsConverterInterface'] ?? $container->load('getRefundUnitsConverterInterfaceService')));
    }
}
