<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestToRefundUnitsConverterInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Converter\Request\RequestToRefundUnitsConverterInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Converter\Request\RequestToRefundUnitsConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Converter/Request/RequestToRefundUnitsConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Converter/Request/RequestToRefundUnitsConverter.php';

        return $container->services['Sylius\\RefundPlugin\\Converter\\Request\\RequestToRefundUnitsConverterInterface'] = new \Sylius\RefundPlugin\Converter\Request\RequestToRefundUnitsConverter(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['Sylius\\RefundPlugin\\Converter\\Request\\RequestToShipmentRefundConverter'] ?? $container->load('getRequestToShipmentRefundConverterService'));
            yield 1 => ($container->services['Sylius\\RefundPlugin\\Converter\\Request\\RequestToOrderItemUnitRefundConverter'] ?? $container->load('getRequestToOrderItemUnitRefundConverterService'));
        }, 2));
    }
}
