<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRelatedPaymentIdProviderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Provider\RelatedPaymentIdProviderInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Provider\DefaultRelatedPaymentIdProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/RelatedPaymentIdProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/DefaultRelatedPaymentIdProvider.php';

        return $container->services['Sylius\\RefundPlugin\\Provider\\RelatedPaymentIdProviderInterface'] = new \Sylius\RefundPlugin\Provider\DefaultRelatedPaymentIdProvider();
    }
}
