<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundNotificationHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'PayPlug\SyliusPayPlugPlugin\Handler\RefundNotificationHandler' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Handler\RefundNotificationHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Handler/RefundNotificationHandler.php';

        return $container->privates['PayPlug\\SyliusPayPlugPlugin\\Handler\\RefundNotificationHandler'] = new \PayPlug\SyliusPayPlugPlugin\Handler\RefundNotificationHandler(($container->services['payplug.repository.payplug_refund_history'] ?? $container->load('getPayplug_Repository_PayplugRefundHistoryService')), ($container->services['payplug_sylius_payplug_plugin.payment_processing.refund_handler'] ?? $container->load('getPayplugSyliusPayplugPlugin_PaymentProcessing_RefundHandlerService')), ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)));
    }
}
