<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundOrderActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\Webhook\RefundOrderAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\Webhook\RefundOrderAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/Webhook/RefundOrderAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/PayPalRefundDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/PayPalRefundDataProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/GenericApiInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/GenericApi.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/RequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ResponseFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ServerRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/StreamFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UploadedFileFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UriFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr17Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr18Client.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\Webhook\\RefundOrderAction'] = new \Sylius\PayPalPlugin\Controller\Webhook\RefundOrderAction(($container->services['sylius_abstraction.state_machine.composite'] ?? self::getSyliusAbstraction_StateMachine_CompositeService($container)), ($container->privates['Sylius\\PayPalPlugin\\Provider\\PaymentProviderInterface'] ?? $container->load('getPaymentProviderInterfaceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \Sylius\PayPalPlugin\Provider\PayPalRefundDataProvider(($container->privates['Sylius\\PayPalPlugin\\Api\\CacheAuthorizeClientApiInterface'] ?? $container->load('getCacheAuthorizeClientApiInterfaceService')), new \Sylius\PayPalPlugin\Api\GenericApi(($container->privates['Http\\Discovery\\Psr18Client'] ??= new \Http\Discovery\Psr18Client()), ($container->privates['http_discovery.psr17_factory'] ??= new \Http\Discovery\Psr17Factory())), ($container->privates['Sylius\\PayPalPlugin\\Provider\\PayPalPaymentMethodProviderInterface'] ?? $container->load('getPayPalPaymentMethodProviderInterfaceService'))));
    }
}
