<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundPaymentMethodsProviderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Provider\RefundPaymentMethodsProviderInterface' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Provider\AmexSupportedRefundPaymentMethodsProviderDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Provider/AbstractSupportedRefundPaymentMethodsProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/RefundPaymentMethodsProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Provider/AmexSupportedRefundPaymentMethodsProviderDecorator.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Provider/ApplePaySupportedRefundPaymentMethodsProviderDecorator.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Provider/BancontactSupportedRefundPaymentMethodsProviderDecorator.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Provider/OneySupportedRefundPaymentMethodsProviderDecorator.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Provider/SupportedRefundPaymentMethodsProviderDecorator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/SupportedRefundPaymentMethodsProvider.php';

        $a = ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack());
        $b = ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container));

        return $container->services['Sylius\\RefundPlugin\\Provider\\RefundPaymentMethodsProviderInterface'] = new \PayPlug\SyliusPayPlugPlugin\Provider\AmexSupportedRefundPaymentMethodsProviderDecorator(new \PayPlug\SyliusPayPlugPlugin\Provider\ApplePaySupportedRefundPaymentMethodsProviderDecorator(new \PayPlug\SyliusPayPlugPlugin\Provider\BancontactSupportedRefundPaymentMethodsProviderDecorator(new \PayPlug\SyliusPayPlugPlugin\Provider\OneySupportedRefundPaymentMethodsProviderDecorator(new \PayPlug\SyliusPayPlugPlugin\Provider\SupportedRefundPaymentMethodsProviderDecorator(new \Sylius\RefundPlugin\Provider\SupportedRefundPaymentMethodsProvider(($container->services['sylius.repository.payment_method'] ?? self::getSylius_Repository_PaymentMethodService($container)), $container->parameters['sylius_refund.supported_gateways']), $a, $b, $container->parameters['sylius_refund.supported_gateways']), $a, $b), $a, $b), $a, $b), $a, $b);
    }
}
