<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestCommandCreatorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Creator\RequestCommandCreatorInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Creator\RefundUnitsCommandCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Creator/RequestCommandCreatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Creator/RefundUnitsCommandCreator.php';

        return $container->services['Sylius\\RefundPlugin\\Creator\\RequestCommandCreatorInterface'] = new \Sylius\RefundPlugin\Creator\RefundUnitsCommandCreator(($container->services['Sylius\\RefundPlugin\\Converter\\Request\\RequestToRefundUnitsConverterInterface'] ?? $container->load('getRequestToRefundUnitsConverterInterfaceService')));
    }
}
