<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundUnitsCommandCreatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Creator\RefundUnitsCommandCreator' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Creator\RefundUnitsCommandCreatorDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Creator/RequestCommandCreatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Creator/RefundUnitsCommandCreatorDecorator.php';

        return $container->services['Sylius\\RefundPlugin\\Creator\\RefundUnitsCommandCreator'] = new \PayPlug\SyliusPayPlugPlugin\Creator\RefundUnitsCommandCreatorDecorator(($container->services['Sylius\\RefundPlugin\\Creator\\RequestCommandCreatorInterface'] ?? $container->load('getRequestCommandCreatorInterfaceService')), ($container->services['Sylius\\RefundPlugin\\Converter\\Request\\RequestToRefundUnitsConverterInterface'] ?? $container->load('getRequestToRefundUnitsConverterInterfaceService')), ($container->services['sylius.repository.payment_method'] ?? self::getSylius_Repository_PaymentMethodService($container)), ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['payplug_sylius_payplug_plugin.api_client.oney'] ?? self::getPayplugSyliusPayplugPlugin_ApiClient_OneyService($container)));
    }
}
