<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundUnitsCommandValidatorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Validator\RefundUnitsCommandValidatorInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Validator\RefundUnitsCommandValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Validator/RefundUnitsCommandValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Validator/RefundUnitsCommandValidator.php';

        return $container->services['Sylius\\RefundPlugin\\Validator\\RefundUnitsCommandValidatorInterface'] = new \Sylius\RefundPlugin\Validator\RefundUnitsCommandValidator(($container->services['Sylius\\RefundPlugin\\Checker\\OrderRefundingAvailabilityChecker'] ?? $container->load('getOrderRefundingAvailabilityCheckerService')), ($container->services['Sylius\\RefundPlugin\\Validator\\RefundAmountValidatorInterface'] ?? $container->load('getRefundAmountValidatorInterfaceService')), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['Sylius\\RefundPlugin\\Validator\\OrderItemUnitRefundsBelongingToOrderValidator'] ?? $container->load('getOrderItemUnitRefundsBelongingToOrderValidatorService'));
            yield 1 => ($container->services['Sylius\\RefundPlugin\\Validator\\ShipmentRefundsBelongingToOrderValidator'] ?? $container->load('getShipmentRefundsBelongingToOrderValidatorService'));
        }, 2));
    }
}
