<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundUnitsHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\CommandHandler\RefundUnitsHandler' shared service.
     *
     * @return \Sylius\RefundPlugin\CommandHandler\RefundUnitsHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/CommandHandler/RefundUnitsHandler.php';

        $a = ($container->privates['debug.traced.sylius.event_bus'] ?? self::getDebug_Traced_Sylius_EventBusService($container));

        if (isset($container->services['Sylius\\RefundPlugin\\CommandHandler\\RefundUnitsHandler'])) {
            return $container->services['Sylius\\RefundPlugin\\CommandHandler\\RefundUnitsHandler'];
        }

        return $container->services['Sylius\\RefundPlugin\\CommandHandler\\RefundUnitsHandler'] = new \Sylius\RefundPlugin\CommandHandler\RefundUnitsHandler(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['Sylius\\RefundPlugin\\Refunder\\OrderItemUnitsRefunder'] ?? $container->load('getOrderItemUnitsRefunderService'));
            yield 1 => ($container->services['Sylius\\RefundPlugin\\Refunder\\OrderShipmentsRefunder'] ?? $container->load('getOrderShipmentsRefunderService'));
        }, 2), $a, ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['Sylius\\RefundPlugin\\Validator\\RefundUnitsCommandValidatorInterface'] ?? $container->load('getRefundUnitsCommandValidatorInterfaceService')));
    }
}
