<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundPaymentCompletedStateApplierInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\StateResolver\RefundPaymentCompletedStateApplierInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\StateResolver\RefundPaymentCompletedStateApplier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/StateResolver/RefundPaymentCompletedStateApplierInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/StateResolver/RefundPaymentCompletedStateApplier.php';

        return $container->services['Sylius\\RefundPlugin\\StateResolver\\RefundPaymentCompletedStateApplierInterface'] = new \Sylius\RefundPlugin\StateResolver\RefundPaymentCompletedStateApplier(($container->services['SM\\Factory\\FactoryInterface'] ?? self::getFactoryInterfaceService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
