<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundCreatorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Creator\RefundCreatorInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Creator\RefundCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Creator/RefundCreatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Creator/RefundCreator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/RefundFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/RefundFactory.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Sylius\\RefundPlugin\\Creator\\RefundCreatorInterface'])) {
            return $container->services['Sylius\\RefundPlugin\\Creator\\RefundCreatorInterface'];
        }

        return $container->services['Sylius\\RefundPlugin\\Creator\\RefundCreatorInterface'] = new \Sylius\RefundPlugin\Creator\RefundCreator(($container->services['sylius_refund.factory.refund'] ??= new \Sylius\RefundPlugin\Factory\RefundFactory('Sylius\\RefundPlugin\\Entity\\Refund')), ($container->services['Sylius\\RefundPlugin\\Provider\\RemainingTotalProviderInterface'] ?? self::getRemainingTotalProviderInterfaceService($container)), ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), $a);
    }
}
