<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundHistoryRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'PayPlug\SyliusPayPlugPlugin\Repository\RefundHistoryRepository' shared service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Repository\RefundHistoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Repository/RefundHistoryRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Repository/RefundHistoryRepository.php';

        return $container->privates['PayPlug\\SyliusPayPlugPlugin\\Repository\\RefundHistoryRepository'] = $container->get('payplug.repository.payplug_refund_history');
    }
}
