<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundUnitsActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'PayPlug\SyliusPayPlugPlugin\Action\Admin\RefundUnitsAction' shared autowired service.
     *
     * @return \PayPlug\SyliusPayPlugPlugin\Action\Admin\RefundUnitsAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payplug/sylius-payplug-plugin/src/Action/Admin/RefundUnitsAction.php';

        return $container->services['PayPlug\\SyliusPayPlugPlugin\\Action\\Admin\\RefundUnitsAction'] = new \PayPlug\SyliusPayPlugPlugin\Action\Admin\RefundUnitsAction(($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['Sylius\\RefundPlugin\\Creator\\RefundUnitsCommandCreator'] ?? $container->load('getRefundUnitsCommandCreatorService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
