<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAbstraction_StateMachine_Adapter_WinzouStateMachineService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_abstraction.state_machine.adapter.winzou_state_machine' shared service.
     *
     * @return \Sylius\Abstraction\StateMachine\WinzouStateMachineAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/state-machine-abstraction/src/WinzouStateMachineAdapter.php';

        $a = ($container->services['SM\\Factory\\FactoryInterface'] ?? self::getFactoryInterfaceService($container));

        if (isset($container->services['sylius_abstraction.state_machine.adapter.winzou_state_machine'])) {
            return $container->services['sylius_abstraction.state_machine.adapter.winzou_state_machine'];
        }

        return $container->services['sylius_abstraction.state_machine.adapter.winzou_state_machine'] = new \Sylius\Abstraction\StateMachine\WinzouStateMachineAdapter($a);
    }
}
