<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_EventBus_Middleware_HandleMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.event_bus.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        $container->privates['sylius.event_bus.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Sylius\\RefundPlugin\\Event\\RefundPaymentGenerated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.G4m0M5d'] ?? $container->load('get_Messenger_HandlerDescriptor_G4m0M5dService'));
        }, 1), 'Symfony\\Component\\Process\\Messenger\\RunProcessMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.fX.nncx'] ?? $container->load('get_Messenger_HandlerDescriptor_FX_NncxService'));
        }, 1), 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.8ZQthfd'] ?? $container->load('get_Messenger_HandlerDescriptor_8ZQthfdService'));
        }, 1), 'Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.KzjMujZ'] ?? $container->load('get_Messenger_HandlerDescriptor_KzjMujZService'));
        }, 1), 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.4lzZe7m'] ?? $container->load('get_Messenger_HandlerDescriptor_4lzZe7mService'));
        }, 1), 'Sylius\\Component\\Promotion\\Event\\CatalogPromotionCreated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.pmxluho'] ?? $container->load('get_Messenger_HandlerDescriptor_PmxluhoService'));
            yield 1 => ($container->privates['.messenger.handler_descriptor.dkVjlTS'] ?? $container->load('get_Messenger_HandlerDescriptor_DkVjlTSService'));
        }, 2), 'Sylius\\Component\\Promotion\\Event\\CatalogPromotionUpdated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.ot8f6qt'] ?? $container->load('get_Messenger_HandlerDescriptor_Ot8f6qtService'));
            yield 1 => ($container->privates['.messenger.handler_descriptor.KpIuBuY'] ?? $container->load('get_Messenger_HandlerDescriptor_KpIuBuYService'));
        }, 2), 'Sylius\\Component\\Promotion\\Event\\CatalogPromotionEnded' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.F2jhGUX'] ?? $container->load('get_Messenger_HandlerDescriptor_F2jhGUXService'));
            yield 1 => ($container->privates['.messenger.handler_descriptor.7ZYWKR0'] ?? $container->load('get_Messenger_HandlerDescriptor_7ZYWKR0Service'));
        }, 2), 'Sylius\\Component\\Core\\Event\\ProductCreated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.BEzrjok'] ?? $container->load('get_Messenger_HandlerDescriptor_BEzrjokService'));
        }, 1), 'Sylius\\Component\\Core\\Event\\ProductUpdated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.RETLWDk'] ?? $container->load('get_Messenger_HandlerDescriptor_RETLWDkService'));
        }, 1), 'Sylius\\Component\\Core\\Event\\ProductVariantCreated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.xnKbskR'] ?? $container->load('get_Messenger_HandlerDescriptor_XnKbskRService'));
        }, 1), 'Sylius\\Component\\Core\\Event\\ProductVariantUpdated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.q9ixaim'] ?? $container->load('get_Messenger_HandlerDescriptor_Q9ixaimService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Event\\OrderCompleted' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.ufR7qhN'] ?? $container->load('get_Messenger_HandlerDescriptor_UfR7qhNService'));
        }, 1), 'Sylius\\RefundPlugin\\Event\\CreditMemoGenerated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.3MUSa7R'] ?? $container->load('get_Messenger_HandlerDescriptor_3MUSa7RService'));
        }, 1), 'Sylius\\RefundPlugin\\Event\\UnitRefundedInterface' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.18HC_Du'] ?? $container->load('get_Messenger_HandlerDescriptor_18HCDuService'));
        }, 1), 'Sylius\\RefundPlugin\\Event\\UnitsRefunded' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.L8USG1h'] ?? $container->load('get_Messenger_HandlerDescriptor_L8USG1hService'));
        }, 1)]), true);

        $instance->setLogger(($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

        return $instance;
    }
}
