<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusRefund_Factory_CreditMemoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_refund.factory.credit_memo' shared service.
     *
     * @return \Sylius\RefundPlugin\Factory\CreditMemoFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/CreditMemoFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/CreditMemoFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Generator/CreditMemoIdentifierGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Generator/UuidCreditMemoIdentifierGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/CurrentDateTimeImmutableProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/CurrentDateTimeImmutableProvider.php';

        $a = ($container->services['Sylius\\RefundPlugin\\Generator\\CreditMemoNumberGeneratorInterface'] ?? $container->load('getCreditMemoNumberGeneratorInterfaceService'));

        if (isset($container->services['sylius_refund.factory.credit_memo'])) {
            return $container->services['sylius_refund.factory.credit_memo'];
        }

        return $container->services['sylius_refund.factory.credit_memo'] = new \Sylius\RefundPlugin\Factory\CreditMemoFactory(new \Sylius\Resource\Factory\Factory('Sylius\\RefundPlugin\\Entity\\CreditMemo'), ($container->services['Sylius\\RefundPlugin\\Generator\\CreditMemoIdentifierGeneratorInterface'] ??= new \Sylius\RefundPlugin\Generator\UuidCreditMemoIdentifierGenerator()), $a, ($container->services['Sylius\\RefundPlugin\\Provider\\CurrentDateTimeImmutableProviderInterface'] ??= new \Sylius\RefundPlugin\Provider\CurrentDateTimeImmutableProvider()));
    }
}
