<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusRefund_Factory_RefundService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_refund.factory.refund' shared service.
     *
     * @return \Sylius\RefundPlugin\Factory\RefundFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/RefundFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/RefundFactory.php';

        return $container->services['sylius_refund.factory.refund'] = new \Sylius\RefundPlugin\Factory\RefundFactory('Sylius\\RefundPlugin\\Entity\\Refund');
    }
}
