<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusRefund_Factory_TaxItemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_refund.factory.tax_item' shared service.
     *
     * @return \Sylius\Resource\Factory\Factory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sylius_refund.factory.tax_item'] = new \Sylius\Resource\Factory\Factory('Sylius\\RefundPlugin\\Entity\\TaxItem');
    }
}
