<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShowPlusInfoCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\CoreBundle\Console\Command\ShowPlusInfoCommand' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Console\Command\ShowPlusInfoCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Console/Command/ShowPlusInfoCommand.php';

        $container->services['Sylius\\Bundle\\CoreBundle\\Console\\Command\\ShowPlusInfoCommand'] = $instance = new \Sylius\Bundle\CoreBundle\Console\Command\ShowPlusInfoCommand();

        $instance->setName('sylius:show-plus-info');
        $instance->setDescription('Shows information about Sylius Plus and Sylius Store');

        return $instance;
    }
}
