<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Controller_PayumService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.controller.payum' shared service.
     *
     * @return \Sylius\Bundle\PayumBundle\Controller\PayumController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Controller/PayumController.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Metadata/MetadataInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/GetStatusFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/GetStatusFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/ResolveNextRouteFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/ResolveNextRouteFactory.php';

        return $container->services['sylius.controller.payum'] = new \Sylius\Bundle\PayumBundle\Controller\PayumController(($container->services['payum'] ?? $container->load('getPayumService')), ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->privates['sylius.resource_registry'] ?? self::getSylius_ResourceRegistryService($container))->get('sylius.order'), ($container->privates['sylius.resource_controller.request_configuration_factory'] ?? $container->load('getSylius_ResourceController_RequestConfigurationFactoryService')), ($container->privates['sylius.resource_controller.view_handler'] ?? $container->load('getSylius_ResourceController_ViewHandlerService')), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['sylius.factory.payum_get_status_action'] ??= new \Sylius\Bundle\PayumBundle\Factory\GetStatusFactory()), ($container->services['sylius.factory.payum_resolve_next_route'] ??= new \Sylius\Bundle\PayumBundle\Factory\ResolveNextRouteFactory()));
    }
}
