<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusRefund_Factory_ShopBillingDataService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_refund.factory.shop_billing_data' shared service.
     *
     * @return \Sylius\RefundPlugin\Factory\ShopBillingDataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/ShopBillingDataFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/ShopBillingDataFactory.php';

        return $container->services['sylius_refund.factory.shop_billing_data'] = new \Sylius\RefundPlugin\Factory\ShopBillingDataFactory(new \Sylius\Resource\Factory\Factory('Sylius\\RefundPlugin\\Entity\\ShopBillingData'));
    }
}
