<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_EmailUpdaterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.email_updater' shared service.
     *
     * @return \Sylius\Bundle\ShopBundle\EventListener\CustomerEmailUpdaterListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EventListener/CustomerEmailUpdaterListener.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['sylius.listener.email_updater'])) {
            return $container->services['sylius.listener.email_updater'];
        }

        return $container->services['sylius.listener.email_updater'] = new \Sylius\Bundle\ShopBundle\EventListener\CustomerEmailUpdaterListener(($container->services['sylius.shop_user.token_generator.email_verification'] ?? $container->load('getSylius_ShopUser_TokenGenerator_EmailVerificationService')), ($container->services['Sylius\\Component\\Channel\\Context\\ChannelContextInterface'] ?? self::getChannelContextInterfaceService($container)), $a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['sylius.section_resolver.uri_based_section_resolver'] ?? self::getSylius_SectionResolver_UriBasedSectionResolverService($container)), ($container->services['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
