<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_ExpiredCartsRemoverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.expired_carts_remover' shared service.
     *
     * @return \Sylius\Bundle\OrderBundle\Remover\ExpiredCartsRemover
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Order/Remover/ExpiredCartsRemoverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Remover/ExpiredCartsRemover.php';

        return $container->services['sylius.expired_carts_remover'] = new \Sylius\Bundle\OrderBundle\Remover\ExpiredCartsRemover(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), '2 days');
    }
}
