<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusRefund_Repository_CreditMemoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_refund.repository.credit_memo' shared service.
     *
     * @return \Sylius\RefundPlugin\Doctrine\ORM\CreditMemoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Repository/CreditMemoRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Doctrine/ORM/CreditMemoRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sylius_refund.repository.credit_memo'])) {
            return $container->services['sylius_refund.repository.credit_memo'];
        }

        return $container->services['sylius_refund.repository.credit_memo'] = new \Sylius\RefundPlugin\Doctrine\ORM\CreditMemoRepository($a, $a->getClassMetadata('Sylius\\RefundPlugin\\Entity\\CreditMemo'));
    }
}
