<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusRefundPlugin_Repository_CreditMemoSequenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_refund_plugin.repository.credit_memo_sequence' shared service.
     *
     * @return \Doctrine\ORM\EntityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sylius_refund_plugin.repository.credit_memo_sequence'])) {
            return $container->services['sylius_refund_plugin.repository.credit_memo_sequence'];
        }

        return $container->services['sylius_refund_plugin.repository.credit_memo_sequence'] = $a->getRepository('Sylius\\RefundPlugin\\Entity\\CreditMemoSequence');
    }
}
