<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShipmentTotalProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Provider\ShipmentTotalProvider' shared service.
     *
     * @return \Sylius\RefundPlugin\Provider\ShipmentTotalProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/RefundUnitTotalProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Provider/ShipmentTotalProvider.php';

        return $container->services['Sylius\\RefundPlugin\\Provider\\ShipmentTotalProvider'] = new \Sylius\RefundPlugin\Provider\ShipmentTotalProvider(($container->services['sylius.repository.adjustment'] ?? $container->load('getSylius_Repository_AdjustmentService')));
    }
}
