<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Controller_Shop_ContactService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.controller.shop.contact' shared service.
     *
     * @return \Sylius\Bundle\ShopBundle\Controller\ContactController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Controller/ContactController.php';

        return $container->services['sylius.controller.shop.contact'] = new \Sylius\Bundle\ShopBundle\Controller\ContactController(($container->services['router'] ?? self::getRouterService($container)), ($container->services['form.factory'] ?? self::getForm_FactoryService($container)), ($container->services['twig'] ?? self::getTwigService($container)), ($container->services['Sylius\\Component\\Channel\\Context\\ChannelContextInterface'] ?? self::getChannelContextInterfaceService($container)), ($container->services['sylius.context.customer'] ?? self::getSylius_Context_CustomerService($container)), ($container->services['Sylius\\Component\\Locale\\Context\\LocaleContextInterface'] ?? self::getLocaleContextInterfaceService($container)), ($container->services['sylius.email_manager.contact'] ?? $container->load('getSylius_EmailManager_ContactService')));
    }
}
