<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendCreditMemoActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Action\Admin\SendCreditMemoAction' shared service.
     *
     * @return \Sylius\RefundPlugin\Action\Admin\SendCreditMemoAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Action/Admin/SendCreditMemoAction.php';

        return $container->services['Sylius\\RefundPlugin\\Action\\Admin\\SendCreditMemoAction'] = new \Sylius\RefundPlugin\Action\Admin\SendCreditMemoAction(($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)), ($container->services['sylius_refund.repository.credit_memo'] ?? $container->load('getSyliusRefund_Repository_CreditMemoService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
