<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendCreditMemoHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\CommandHandler\SendCreditMemoHandler' shared service.
     *
     * @return \Sylius\RefundPlugin\CommandHandler\SendCreditMemoHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/CommandHandler/SendCreditMemoHandler.php';

        return $container->services['Sylius\\RefundPlugin\\CommandHandler\\SendCreditMemoHandler'] = new \Sylius\RefundPlugin\CommandHandler\SendCreditMemoHandler(($container->services['sylius_refund.repository.credit_memo'] ?? $container->load('getSyliusRefund_Repository_CreditMemoService')), ($container->services['Sylius\\RefundPlugin\\Sender\\CreditMemoEmailSenderInterface'] ?? $container->load('getCreditMemoEmailSenderInterfaceService')));
    }
}
