<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShowPlusInfoCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Sylius\Bundle\CoreBundle\Console\Command\ShowPlusInfoCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Sylius\\Bundle\\CoreBundle\\Console\\Command\\ShowPlusInfoCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sylius:show-plus-info', [], 'Shows information about Sylius Plus and Sylius Store', false, #[\Closure(name: 'Sylius\\Bundle\\CoreBundle\\Console\\Command\\ShowPlusInfoCommand')] fn (): \Sylius\Bundle\CoreBundle\Console\Command\ShowPlusInfoCommand => ($container->services['Sylius\\Bundle\\CoreBundle\\Console\\Command\\ShowPlusInfoCommand'] ?? $container->load('getShowPlusInfoCommandService')));
    }
}
