<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusRefund_Repository_LineItemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_refund.repository.line_item' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sylius_refund.repository.line_item'])) {
            return $container->services['sylius_refund.repository.line_item'];
        }

        return $container->services['sylius_refund.repository.line_item'] = $a->getRepository('Sylius\\RefundPlugin\\Entity\\LineItem');
    }
}
