<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusRefund_Factory_RefundPaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_refund.factory.refund_payment' shared service.
     *
     * @return \Sylius\RefundPlugin\Factory\RefundPaymentFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/RefundPaymentFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Factory/RefundPaymentFactory.php';

        return $container->services['sylius_refund.factory.refund_payment'] = new \Sylius\RefundPlugin\Factory\RefundPaymentFactory('Sylius\\RefundPlugin\\Entity\\RefundPayment');
    }
}
