<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwigToPdfGeneratorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Generator\TwigToPdfGeneratorInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Generator\TwigToPdfGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Generator/TwigToPdfGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Generator/TwigToPdfGenerator.php';

        return $container->services['Sylius\\RefundPlugin\\Generator\\TwigToPdfGeneratorInterface'] = new \Sylius\RefundPlugin\Generator\TwigToPdfGenerator(($container->services['twig'] ?? self::getTwigService($container)), ($container->services['knp_snappy.pdf'] ?? $container->load('getKnpSnappy_PdfService')), ($container->services['Sylius\\RefundPlugin\\Generator\\PdfOptionsGeneratorInterface'] ?? $container->load('getPdfOptionsGeneratorInterfaceService')));
    }
}
