<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnitRefundedEventListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Listener\UnitRefundedEventListener' shared service.
     *
     * @return \Sylius\RefundPlugin\Listener\UnitRefundedEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Listener/UnitRefundedEventListener.php';

        $a = ($container->services['Sylius\\RefundPlugin\\StateResolver\\OrderPartiallyRefundedStateResolverInterface'] ?? $container->load('getOrderPartiallyRefundedStateResolverInterfaceService'));

        if (isset($container->services['Sylius\\RefundPlugin\\Listener\\UnitRefundedEventListener'])) {
            return $container->services['Sylius\\RefundPlugin\\Listener\\UnitRefundedEventListener'];
        }

        return $container->services['Sylius\\RefundPlugin\\Listener\\UnitRefundedEventListener'] = new \Sylius\RefundPlugin\Listener\UnitRefundedEventListener($a);
    }
}
