<?php

namespace ContainerQV97orU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnitRefundFilterInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\RefundPlugin\Filter\UnitRefundFilterInterface' shared service.
     *
     * @return \Sylius\RefundPlugin\Filter\UnitRefundFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Filter/UnitRefundFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/refund-plugin/src/Filter/UnitRefundFilter.php';

        return $container->services['Sylius\\RefundPlugin\\Filter\\UnitRefundFilterInterface'] = new \Sylius\RefundPlugin\Filter\UnitRefundFilter();
    }
}
