<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdjustmentOrderProviderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\Provider\AdjustmentOrderProviderInterface' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Provider\AdjustmentOrderProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Provider/AdjustmentOrderProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Provider/AdjustmentOrderProvider.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\Provider\\AdjustmentOrderProviderInterface'] = new \Sylius\Bundle\ApiBundle\Provider\AdjustmentOrderProvider();
    }
}
