<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributesOperationRouteFactoryInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Resource\Symfony\Routing\Factory\AttributesOperationRouteFactoryInterface' shared service.
     *
     * @return \Sylius\Resource\Symfony\Routing\Factory\AttributesOperationRouteFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Routing/Factory/AttributesOperationRouteFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Routing/Factory/AttributesOperationRouteFactory.php';

        return $container->services['Sylius\\Resource\\Symfony\\Routing\\Factory\\AttributesOperationRouteFactoryInterface'] = new \Sylius\Resource\Symfony\Routing\Factory\AttributesOperationRouteFactory(($container->privates['sylius.resource_registry'] ?? self::getSylius_ResourceRegistryService($container)), ($container->services['Sylius\\Resource\\Symfony\\Routing\\Factory\\OperationRouteFactoryInterface'] ?? $container->load('getOperationRouteFactoryInterfaceService')), ($container->privates['sylius.resource_metadata_collection.factory.templates_dir'] ?? self::getSylius_ResourceMetadataCollection_Factory_TemplatesDirService($container)));
    }
}
