<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChooseShippingMethodHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\CommandHandler\Checkout\ChooseShippingMethodHandler' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\CommandHandler\Checkout\ChooseShippingMethodHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChooseShippingMethodHandler.php';

        $a = ($container->services['SM\\Factory\\FactoryInterface'] ?? self::getFactoryInterfaceService($container));

        if (isset($container->services['Sylius\\Bundle\\ApiBundle\\CommandHandler\\Checkout\\ChooseShippingMethodHandler'])) {
            return $container->services['Sylius\\Bundle\\ApiBundle\\CommandHandler\\Checkout\\ChooseShippingMethodHandler'];
        }

        return $container->services['Sylius\\Bundle\\ApiBundle\\CommandHandler\\Checkout\\ChooseShippingMethodHandler'] = new \Sylius\Bundle\ApiBundle\CommandHandler\Checkout\ChooseShippingMethodHandler(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['sylius.repository.shipping_method'] ?? self::getSylius_Repository_ShippingMethodService($container)), ($container->services['sylius.repository.shipment'] ?? self::getSylius_Repository_ShipmentService($container)), ($container->services['sylius.shipping_method_eligibility_checker'] ?? self::getSylius_ShippingMethodEligibilityCheckerService($container)), $a);
    }
}
