<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCancelLastPayPalPaymentActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\CancelLastPayPalPaymentAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\CancelLastPayPalPaymentAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/CancelLastPayPalPaymentAction.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\CancelLastPayPalPaymentAction'] = new \Sylius\PayPalPlugin\Controller\CancelLastPayPalPaymentAction(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sylius_abstraction.state_machine.composite'] ?? self::getSyliusAbstraction_StateMachine_CompositeService($container)), ($container->services['sylius.order_processing.order_payment_processor.checkout'] ?? $container->load('getSylius_OrderProcessing_OrderPaymentProcessor_CheckoutService')), ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)));
    }
}
