<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreatePayPalOrderFromCartActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\CreatePayPalOrderFromCartAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\CreatePayPalOrderFromCartAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/CreatePayPalOrderFromCartAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Payment/Remover/OrderPaymentsRemoverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Payment/Remover/OrderPaymentsRemover.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\CreatePayPalOrderFromCartAction'] = new \Sylius\PayPalPlugin\Controller\CreatePayPalOrderFromCartAction(NULL, NULL, NULL, ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['Sylius\\PayPalPlugin\\Provider\\OrderProviderInterface'] ?? $container->load('getOrderProviderInterfaceService')), ($container->privates['Sylius\\PayPalPlugin\\Resolver\\CapturePaymentResolverInterface'] ?? $container->load('getCapturePaymentResolverInterfaceService')), ($container->services['Sylius\\Component\\Core\\Payment\\Remover\\OrderPaymentsRemoverInterface'] ??= new \Sylius\Component\Core\Payment\Remover\OrderPaymentsRemover()), ($container->services['sylius.order_processing.order_processor'] ?? $container->load('getSylius_OrderProcessing_OrderProcessorService')));
    }
}
