<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnableSellerActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\EnableSellerAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\EnableSellerAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/EnableSellerAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Enabler/PaymentMethodEnablerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Enabler/PayPalPaymentMethodEnabler.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/RequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ResponseFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ServerRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/StreamFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UploadedFileFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UriFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr17Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr18Client.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\EnableSellerAction'] = new \Sylius\PayPalPlugin\Controller\EnableSellerAction(($container->services['sylius.repository.payment_method'] ?? self::getSylius_Repository_PaymentMethodService($container)), new \Sylius\PayPalPlugin\Enabler\PayPalPaymentMethodEnabler(($container->privates['Http\\Discovery\\Psr18Client'] ??= new \Http\Discovery\Psr18Client()), 'https://paypal.sylius.com', ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['Sylius\\PayPalPlugin\\Registrar\\SellerWebhookRegistrarInterface'] ?? $container->load('getSellerWebhookRegistrarInterfaceService')), ($container->privates['http_discovery.psr17_factory'] ??= new \Http\Discovery\Psr17Factory())));
    }
}
