<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessPayPalOrderActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\ProcessPayPalOrderAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\ProcessPayPalOrderAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/ProcessPayPalOrderAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Verifier/PaymentAmountVerifierInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Verifier/PaymentAmountVerifier.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\ProcessPayPalOrderAction'] = new \Sylius\PayPalPlugin\Controller\ProcessPayPalOrderAction(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['sylius.repository.customer'] ?? $container->load('getSylius_Repository_CustomerService')), ($container->services['sylius.factory.customer'] ??= new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Customer\\Customer')), ($container->services['sylius.factory.address'] ?? $container->load('getSylius_Factory_AddressService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sylius_abstraction.state_machine.composite'] ?? self::getSyliusAbstraction_StateMachine_CompositeService($container)), ($container->privates['Sylius\\PayPalPlugin\\Manager\\PaymentStateManagerInterface'] ?? $container->load('getPaymentStateManagerInterfaceService')), ($container->privates['Sylius\\PayPalPlugin\\Api\\CacheAuthorizeClientApiInterface'] ?? $container->load('getCacheAuthorizeClientApiInterfaceService')), ($container->privates['Sylius\\PayPalPlugin\\Api\\OrderDetailsApiInterface'] ?? $container->load('getOrderDetailsApiInterfaceService')), ($container->privates['Sylius\\PayPalPlugin\\Provider\\OrderProviderInterface'] ?? $container->load('getOrderProviderInterfaceService')), ($container->privates['sylius_paypal.verifier.payment_amount'] ??= new \Sylius\PayPalPlugin\Verifier\PaymentAmountVerifier()));
    }
}
