<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentItemDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\DataProvider\PaymentItemDataProvider' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\DataProvider\PaymentItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/DataProvider/PaymentItemDataProvider.php';

        $a = ($container->services['sylius.repository.payment'] ?? $container->load('getSylius_Repository_PaymentService'));

        if (isset($container->services['Sylius\\Bundle\\ApiBundle\\DataProvider\\PaymentItemDataProvider'])) {
            return $container->services['Sylius\\Bundle\\ApiBundle\\DataProvider\\PaymentItemDataProvider'];
        }

        return $container->services['Sylius\\Bundle\\ApiBundle\\DataProvider\\PaymentItemDataProvider'] = new \Sylius\Bundle\ApiBundle\DataProvider\PaymentItemDataProvider($a, ($container->services['Sylius\\Bundle\\ApiBundle\\Context\\UserContextInterface'] ?? self::getUserContextInterfaceService($container)));
    }
}
