<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentPreCompleteListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\CoreBundle\EventListener\PaymentPreCompleteListener' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\PaymentPreCompleteListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/PaymentPreCompleteListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Inventory/Checker/OrderItemAvailabilityCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Inventory/Checker/OrderItemAvailabilityChecker.php';

        return $container->services['Sylius\\Bundle\\CoreBundle\\EventListener\\PaymentPreCompleteListener'] = new \Sylius\Bundle\CoreBundle\EventListener\PaymentPreCompleteListener(($container->services['sylius.inventory.order_item_availability_checker'] ??= new \Sylius\Component\Core\Inventory\Checker\OrderItemAvailabilityChecker()));
    }
}
