<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalClientInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\Client\PayPalClientInterface' shared service.
     *
     * @return \Sylius\PayPalPlugin\Client\PayPalClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Client/PayPalClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Client/PayPalClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/RequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ResponseFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ServerRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/StreamFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UploadedFileFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UriFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr17Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr18Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/UuidProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/UuidProvider.php';

        $a = ($container->privates['http_discovery.psr17_factory'] ??= new \Http\Discovery\Psr17Factory());

        return $container->privates['Sylius\\PayPalPlugin\\Client\\PayPalClientInterface'] = new \Sylius\PayPalPlugin\Client\PayPalClient(($container->privates['Http\\Discovery\\Psr18Client'] ??= new \Http\Discovery\Psr18Client()), ($container->services['monolog.logger.paypal'] ?? $container->load('getMonolog_Logger_PaypalService')), ($container->privates['Sylius\\PayPalPlugin\\Provider\\UuidProviderInterface'] ??= new \Sylius\PayPalPlugin\Provider\UuidProvider()), ($container->privates['Sylius\\PayPalPlugin\\Provider\\PayPalConfigurationProviderInterface'] ?? $container->load('getPayPalConfigurationProviderInterfaceService')), ($container->services['Sylius\\Component\\Channel\\Context\\ChannelContextInterface'] ?? self::getChannelContextInterfaceService($container)), 'https://api.sandbox.paypal.com/', 5, false, $a, $a);
    }
}
