<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenderRequestPasswordResetPageActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\AdminBundle\Action\Account\RenderRequestPasswordResetPageAction' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Action\Account\RenderRequestPasswordResetPageAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Action/Account/RenderRequestPasswordResetPageAction.php';

        return $container->services['Sylius\\Bundle\\AdminBundle\\Action\\Account\\RenderRequestPasswordResetPageAction'] = new \Sylius\Bundle\AdminBundle\Action\Account\RenderRequestPasswordResetPageAction(($container->services['twig'] ?? self::getTwigService($container)), ($container->services['form.factory'] ?? self::getForm_FactoryService($container)));
    }
}
