<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenderResetPasswordPageActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\AdminBundle\Action\Account\RenderResetPasswordPageAction' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Action\Account\RenderResetPasswordPageAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Action/Account/RenderResetPasswordPageAction.php';

        return $container->services['Sylius\\Bundle\\AdminBundle\\Action\\Account\\RenderResetPasswordPageAction'] = new \Sylius\Bundle\AdminBundle\Action\Account\RenderResetPasswordPageAction(($container->services['sylius.repository.admin_user'] ?? $container->load('getSylius_Repository_AdminUserService')), ($container->services['form.factory'] ?? self::getForm_FactoryService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['twig'] ?? self::getTwigService($container)), 'P1D');
    }
}
