<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_Manager_ShopService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authenticator.manager.shop' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authentication\AuthenticatorManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticatorManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/UserAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticatorManager.php';

        $a = ($container->privates['security.authenticator.form_login.shop'] ?? $container->load('getSecurity_Authenticator_FormLogin_ShopService'));

        if (isset($container->privates['security.authenticator.manager.shop'])) {
            return $container->privates['security.authenticator.manager.shop'];
        }

        return $container->privates['security.authenticator.manager.shop'] = new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([$a, ($container->privates['security.authenticator.remember_me.shop'] ?? $container->load('getSecurity_Authenticator_RememberMe_ShopService'))], ($container->services['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['debug.security.event_dispatcher.shop'] ?? self::getDebug_Security_EventDispatcher_ShopService($container)), 'shop', ($container->privates['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container)), true, true, []);
    }
}
