<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Controller_Shop_CurrencySwitchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.controller.shop.currency_switch' shared service.
     *
     * @return \Sylius\Bundle\ShopBundle\Controller\CurrencySwitchController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Controller/CurrencySwitchController.php';

        return $container->services['sylius.controller.shop.currency_switch'] = new \Sylius\Bundle\ShopBundle\Controller\CurrencySwitchController(($container->services['twig'] ?? self::getTwigService($container)), ($container->services['sylius.context.currency.channel_aware'] ?? self::getSylius_Context_Currency_ChannelAwareService($container)), ($container->services['sylius.storage.currency'] ?? self::getSylius_Storage_CurrencyService($container)), ($container->services['Sylius\\Component\\Channel\\Context\\ChannelContextInterface'] ?? self::getChannelContextInterfaceService($container)));
    }
}
