<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSellerWebhookRegistrarInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\Registrar\SellerWebhookRegistrarInterface' shared service.
     *
     * @return \Sylius\PayPalPlugin\Registrar\SellerWebhookRegistrar
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Registrar/SellerWebhookRegistrarInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Registrar/SellerWebhookRegistrar.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/WebhookApiInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/WebhookApi.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/RequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ResponseFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ServerRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/StreamFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UploadedFileFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UriFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr17Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr18Client.php';

        $a = ($container->privates['http_discovery.psr17_factory'] ??= new \Http\Discovery\Psr17Factory());

        return $container->privates['Sylius\\PayPalPlugin\\Registrar\\SellerWebhookRegistrarInterface'] = new \Sylius\PayPalPlugin\Registrar\SellerWebhookRegistrar(($container->privates['Sylius\\PayPalPlugin\\Api\\AuthorizeClientApiInterface'] ?? $container->load('getAuthorizeClientApiInterfaceService')), ($container->services['router'] ?? self::getRouterService($container)), new \Sylius\PayPalPlugin\Api\WebhookApi(($container->privates['Http\\Discovery\\Psr18Client'] ??= new \Http\Discovery\Psr18Client()), 'https://api.sandbox.paypal.com/', $a, $a));
    }
}
