<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Grid_FilterStorageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.grid.filter_storage' shared service.
     *
     * @return \Sylius\Bundle\GridBundle\Storage\SessionFilterStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Bundle/Storage/FilterStorageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Bundle/Storage/SessionFilterStorage.php';

        return $container->services['sylius.grid.filter_storage'] = new \Sylius\Bundle\GridBundle\Storage\SessionFilterStorage(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
