<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_ShippingMethodChoiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.shipping_method_choice' shared service.
     *
     * @return \Sylius\Bundle\ShippingBundle\Form\Type\ShippingMethodChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php';

        return $container->services['sylius.form.type.shipping_method_choice'] = new \Sylius\Bundle\ShippingBundle\Form\Type\ShippingMethodChoiceType(($container->services['sylius.shipping_methods_resolver'] ?? self::getSylius_ShippingMethodsResolverService($container)), ($container->services['sylius.registry.shipping_calculator'] ?? self::getSylius_Registry_ShippingCalculatorService($container)), ($container->services['sylius.repository.shipping_method'] ?? self::getSylius_Repository_ShippingMethodService($container)));
    }
}
