<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Fixture_OrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.fixture.order' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Fixture\OrderFixture
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php';

        return $container->services['sylius.fixture.order'] = new \Sylius\Bundle\CoreBundle\Fixture\OrderFixture(($container->services['sylius.custom_factory.order'] ?? self::getSylius_CustomFactory_OrderService($container)), ($container->services['sylius.factory.cart_item'] ?? $container->load('getSylius_Factory_CartItemService')), ($container->services['sylius.order_item_quantity_modifier.limiting'] ?? $container->load('getSylius_OrderItemQuantityModifier_LimitingService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sylius.repository.channel'] ?? self::getSylius_Repository_ChannelService($container)), ($container->services['sylius.repository.customer'] ?? $container->load('getSylius_Repository_CustomerService')), ($container->services['sylius.repository.product'] ?? $container->load('getSylius_Repository_ProductService')), ($container->services['sylius.repository.country'] ?? $container->load('getSylius_Repository_CountryService')), ($container->services['sylius.repository.payment_method'] ?? self::getSylius_Repository_PaymentMethodService($container)), ($container->services['sylius.repository.shipping_method'] ?? self::getSylius_Repository_ShippingMethodService($container)), ($container->services['sylius.factory.address'] ?? $container->load('getSylius_Factory_AddressService')), ($container->services['SM\\Factory\\FactoryInterface'] ?? self::getFactoryInterfaceService($container)), ($container->services['sylius.checker.order_shipping_method_selection_requirement'] ?? self::getSylius_Checker_OrderShippingMethodSelectionRequirementService($container)), ($container->services['sylius.checker.order_payment_method_selection_requirement'] ?? self::getSylius_Checker_OrderPaymentMethodSelectionRequirementService($container)), ($container->services['sylius.fixture.example_factory.order'] ?? $container->load('getSylius_Fixture_ExampleFactory_OrderService')));
    }
}
