<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Twig_Extension_TaxesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.twig.extension.taxes' shared service.
     *
     * @return \Sylius\Bundle\ShopBundle\Twig\OrderTaxesTotalExtension
     *
     * @deprecated Since sylius/shop-bundle 1.12: The "sylius.twig.extension.taxes" is deprecated since Sylius 1.12 and will be removed in 2.0. Use methods "getTaxExcludedTotal" and "getTaxIncludedTotal" from "Sylius\Component\Core\Model\Order" instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('sylius/shop-bundle', '1.12', 'The "sylius.twig.extension.taxes" is deprecated since Sylius 1.12 and will be removed in 2.0. Use methods "getTaxExcludedTotal" and "getTaxIncludedTotal" from "Sylius\\Component\\Core\\Model\\Order" instead.');

        return new \Sylius\Bundle\ShopBundle\Twig\OrderTaxesTotalExtension();
    }
}
