<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShipmentItemDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\DataProvider\ShipmentItemDataProvider' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\DataProvider\ShipmentItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/DataProvider/ShipmentItemDataProvider.php';

        $a = ($container->services['sylius.repository.shipment'] ?? self::getSylius_Repository_ShipmentService($container));

        if (isset($container->services['Sylius\\Bundle\\ApiBundle\\DataProvider\\ShipmentItemDataProvider'])) {
            return $container->services['Sylius\\Bundle\\ApiBundle\\DataProvider\\ShipmentItemDataProvider'];
        }

        return $container->services['Sylius\\Bundle\\ApiBundle\\DataProvider\\ShipmentItemDataProvider'] = new \Sylius\Bundle\ApiBundle\DataProvider\ShipmentItemDataProvider($a, ($container->services['Sylius\\Bundle\\ApiBundle\\Context\\UserContextInterface'] ?? self::getUserContextInterfaceService($container)));
    }
}
