<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_MainControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.main_controller' shared service.
     *
     * @return \Sylius\Resource\Symfony\Controller\MainController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Controller/MainController.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Context/Initiator/RequestContextInitiatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Context/Initiator/LegacyRequestContextInitiator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Context/Initiator/RequestContextInitiator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/ProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Validator/State/ValidateProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Form/State/FormProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Serializer/State/DeserializeProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/EventDispatcher/State/DispatchPostReadEventProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/Provider/FactoryProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/Provider/ReadProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/Provider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/FactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/ExpressionLanguage/ArgumentParserInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/ExpressionLanguage/ArgumentParser.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/ExpressionLanguage/VariablesCollectionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/ExpressionLanguage/VariablesCollection.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/EventDispatcher/OperationEventDispatcherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/EventDispatcher/OperationEventDispatcher.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/Processor/WriteProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Serializer/State/SerializeProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/Processor/FlashProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/Processor/RespondProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/ResponderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/Responder.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Session/Flash/FlashHelperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Session/Flash/FlashHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/Processor/BulkAwareProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/EventDispatcher/State/DispatchPostWriteEventProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/EventDispatcher/State/DispatchPreWriteEventProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/Processor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/EventDispatcher/OperationEventHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/EventDispatcher/OperationEventHandler.php';

        $a = new \Sylius\Resource\Symfony\EventDispatcher\OperationEventDispatcher(($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));
        $b = ($container->privates['serializer'] ?? self::getSerializerService($container));
        $c = new \Sylius\Resource\Symfony\Session\Flash\FlashHelper(($container->services['translator'] ?? self::getTranslatorService($container)));
        $d = new \Sylius\Resource\Symfony\EventDispatcher\OperationEventHandler(($container->services['sylius.routing.redirect_handler'] ?? $container->load('getSylius_Routing_RedirectHandlerService')), $c);

        return $container->services['sylius.main_controller'] = new \Sylius\Resource\Symfony\Controller\MainController(($container->privates['sylius.resource_metadata_operation.initiator.http_operation'] ?? self::getSylius_ResourceMetadataOperation_Initiator_HttpOperationService($container)), new \Sylius\Bundle\ResourceBundle\Context\Initiator\LegacyRequestContextInitiator(($container->privates['sylius.resource_registry'] ?? self::getSylius_ResourceRegistryService($container)), ($container->privates['sylius.resource_controller.request_configuration_factory'] ?? $container->load('getSylius_ResourceController_RequestConfigurationFactoryService')), new \Sylius\Resource\Context\Initiator\RequestContextInitiator()), new \Sylius\Resource\Symfony\Validator\State\ValidateProvider(new \Sylius\Resource\Symfony\Form\State\FormProvider(new \Sylius\Resource\Symfony\Serializer\State\DeserializeProvider(new \Sylius\Resource\Symfony\EventDispatcher\State\DispatchPostReadEventProvider(new \Sylius\Resource\State\Provider\FactoryProvider(new \Sylius\Resource\State\Provider\ReadProvider(new \Sylius\Resource\State\Provider(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Sylius\\Resource\\Grid\\State\\RequestGridProvider' => ['privates', 'Sylius\\Resource\\Grid\\State\\RequestGridProvider', 'getRequestGridProviderService', true],
            'Sylius\\Resource\\Symfony\\Request\\State\\Provider' => ['privates', 'Sylius\\Resource\\Symfony\\Request\\State\\Provider', 'getProvider2Service', true],
        ], [
            'Sylius\\Resource\\Grid\\State\\RequestGridProvider' => 'Sylius\\Resource\\Grid\\State\\RequestGridProvider',
            'Sylius\\Resource\\Symfony\\Request\\State\\Provider' => 'Sylius\\Resource\\Symfony\\Request\\State\\Provider',
        ]))), new \Sylius\Resource\State\Factory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sylius.factory.address' => ['services', 'sylius.factory.address', 'getSylius_Factory_AddressService', true],
            'sylius.factory.address_log_entry' => ['services', 'sylius.factory.address_log_entry', 'getSylius_Factory_AddressLogEntryService', true],
            'sylius.factory.adjustment' => ['services', 'Sylius\\Component\\Order\\Factory\\AdjustmentFactoryInterface', 'getAdjustmentFactoryInterfaceService', true],
            'sylius.factory.avatar_image' => ['services', 'sylius.factory.avatar_image', 'getSylius_Factory_AvatarImageService', true],
            'sylius.factory.catalog_promotion' => ['services', 'sylius.factory.catalog_promotion', 'getSylius_Factory_CatalogPromotionService', true],
            'sylius.factory.catalog_promotion_action' => ['services', 'sylius.factory.catalog_promotion_action', 'getSylius_Factory_CatalogPromotionActionService', true],
            'sylius.factory.catalog_promotion_scope' => ['services', 'sylius.factory.catalog_promotion_scope', 'getSylius_Factory_CatalogPromotionScopeService', true],
            'sylius.factory.catalog_promotion_translation' => ['services', 'sylius.factory.catalog_promotion_translation', 'getSylius_Factory_CatalogPromotionTranslationService', true],
            'sylius.factory.channel' => ['services', 'Sylius\\Component\\Channel\\Factory\\ChannelFactoryInterface', 'getChannelFactoryInterfaceService', true],
            'sylius.factory.channel_pricing' => ['services', 'sylius.factory.channel_pricing', 'getSylius_Factory_ChannelPricingService', true],
            'sylius.factory.country' => ['services', 'sylius.factory.country', 'getSylius_Factory_CountryService', true],
            'sylius.factory.currency' => ['services', 'sylius.factory.currency', 'getSylius_Factory_CurrencyService', true],
            'sylius.factory.customer' => ['services', 'sylius.factory.customer', 'getSylius_Factory_CustomerService', true],
            'sylius.factory.customer_group' => ['services', 'sylius.factory.customer_group', 'getSylius_Factory_CustomerGroupService', true],
            'sylius.factory.exchange_rate' => ['services', 'sylius.factory.exchange_rate', 'getSylius_Factory_ExchangeRateService', true],
            'sylius.factory.gateway_config' => ['services', 'sylius.factory.gateway_config', 'getSylius_Factory_GatewayConfigService', true],
            'sylius.factory.inventory_unit' => ['services', 'sylius.factory.inventory_unit', 'getSylius_Factory_InventoryUnitService', true],
            'sylius.factory.locale' => ['services', 'sylius.factory.locale', 'getSylius_Factory_LocaleService', true],
            'sylius.factory.oauth_user' => ['services', 'sylius.factory.oauth_user', 'getSylius_Factory_OauthUserService', true],
            'sylius.factory.order' => ['services', 'sylius.custom_factory.order', 'getSylius_CustomFactory_OrderService', false],
            'sylius.factory.order_item' => ['services', 'sylius.factory.cart_item', 'getSylius_Factory_CartItemService', true],
            'sylius.factory.order_item_unit' => ['services', 'sylius.factory.order_item_unit', 'getSylius_Factory_OrderItemUnitService', true],
            'sylius.factory.order_sequence' => ['services', 'sylius.factory.order_sequence', 'getSylius_Factory_OrderSequenceService', true],
            'sylius.factory.payment' => ['services', 'Sylius\\Component\\Payment\\Factory\\PaymentFactoryInterface', 'getPaymentFactoryInterfaceService', true],
            'sylius.factory.payment_method' => ['services', 'Sylius\\Component\\Core\\Factory\\PaymentMethodFactoryInterface', 'getPaymentMethodFactoryInterfaceService', true],
            'sylius.factory.payment_method_translation' => ['services', 'sylius.factory.payment_method_translation', 'getSylius_Factory_PaymentMethodTranslationService', true],
            'sylius.factory.payment_security_token' => ['services', 'sylius.factory.payment_security_token', 'getSylius_Factory_PaymentSecurityTokenService', true],
            'sylius.factory.product' => ['services', 'Sylius\\Component\\Product\\Factory\\ProductFactoryInterface', 'getProductFactoryInterfaceService', true],
            'sylius.factory.product_association' => ['services', 'sylius.factory.product_association', 'getSylius_Factory_ProductAssociationService', true],
            'sylius.factory.product_association_type' => ['services', 'sylius.factory.product_association_type', 'getSylius_Factory_ProductAssociationTypeService', true],
            'sylius.factory.product_association_type_translation' => ['services', 'sylius.factory.product_association_type_translation', 'getSylius_Factory_ProductAssociationTypeTranslationService', true],
            'sylius.factory.product_attribute_translation' => ['services', 'sylius.factory.product_attribute_translation', 'getSylius_Factory_ProductAttributeTranslationService', true],
            'sylius.factory.product_attribute_value' => ['services', 'sylius.factory.product_attribute_value', 'getSylius_Factory_ProductAttributeValueService', true],
            'sylius.factory.product_image' => ['services', 'sylius.factory.product_image', 'getSylius_Factory_ProductImageService', true],
            'sylius.factory.product_option' => ['services', 'sylius.factory.product_option', 'getSylius_Factory_ProductOptionService', true],
            'sylius.factory.product_option_translation' => ['services', 'sylius.factory.product_option_translation', 'getSylius_Factory_ProductOptionTranslationService', true],
            'sylius.factory.product_option_value' => ['services', 'sylius.factory.product_option_value', 'getSylius_Factory_ProductOptionValueService', true],
            'sylius.factory.product_option_value_translation' => ['services', 'sylius.factory.product_option_value_translation', 'getSylius_Factory_ProductOptionValueTranslationService', true],
            'sylius.factory.product_reviewer' => ['services', 'sylius.factory.product_reviewer', 'getSylius_Factory_ProductReviewerService', true],
            'sylius.factory.product_taxon' => ['services', 'sylius.factory.product_taxon', 'getSylius_Factory_ProductTaxonService', true],
            'sylius.factory.product_translation' => ['services', 'sylius.factory.product_translation', 'getSylius_Factory_ProductTranslationService', true],
            'sylius.factory.product_variant' => ['services', 'Sylius\\Component\\Product\\Factory\\ProductVariantFactoryInterface', 'getProductVariantFactoryInterfaceService', true],
            'sylius.factory.product_variant_translation' => ['services', 'sylius.factory.product_variant_translation', 'getSylius_Factory_ProductVariantTranslationService', true],
            'sylius.factory.promotion' => ['services', 'sylius.factory.promotion', 'getSylius_Factory_PromotionService', true],
            'sylius.factory.promotion_action' => ['services', 'Sylius\\Component\\Core\\Factory\\PromotionActionFactoryInterface', 'getPromotionActionFactoryInterfaceService', true],
            'sylius.factory.promotion_coupon' => ['services', 'Sylius\\Component\\Promotion\\Factory\\PromotionCouponFactoryInterface', 'getPromotionCouponFactoryInterfaceService', true],
            'sylius.factory.promotion_rule' => ['services', 'Sylius\\Component\\Core\\Factory\\PromotionRuleFactoryInterface', 'getPromotionRuleFactoryInterfaceService', true],
            'sylius.factory.province' => ['services', 'sylius.factory.province', 'getSylius_Factory_ProvinceService', true],
            'sylius.factory.shipment' => ['services', 'sylius.factory.shipment', 'getSylius_Factory_ShipmentService', true],
            'sylius.factory.shipment_unit' => ['services', 'sylius.factory.shipment_unit', 'getSylius_Factory_ShipmentUnitService', true],
            'sylius.factory.shipping_category' => ['services', 'sylius.factory.shipping_category', 'getSylius_Factory_ShippingCategoryService', true],
            'sylius.factory.shipping_method' => ['services', 'sylius.factory.shipping_method', 'getSylius_Factory_ShippingMethodService', true],
            'sylius.factory.shipping_method_rule' => ['services', 'sylius.factory.shipping_method_rule', 'getSylius_Factory_ShippingMethodRuleService', true],
            'sylius.factory.shipping_method_translation' => ['services', 'sylius.factory.shipping_method_translation', 'getSylius_Factory_ShippingMethodTranslationService', true],
            'sylius.factory.shop_billing_data' => ['services', 'sylius.factory.shop_billing_data', 'getSylius_Factory_ShopBillingDataService', true],
            'sylius.factory.tax_category' => ['services', 'sylius.factory.tax_category', 'getSylius_Factory_TaxCategoryService', true],
            'sylius.factory.tax_rate' => ['services', 'sylius.factory.tax_rate', 'getSylius_Factory_TaxRateService', true],
            'sylius.factory.taxon' => ['services', 'Sylius\\Component\\Taxonomy\\Factory\\TaxonFactoryInterface', 'getTaxonFactoryInterfaceService', true],
            'sylius.factory.taxon_image' => ['services', 'sylius.factory.taxon_image', 'getSylius_Factory_TaxonImageService', true],
            'sylius.factory.taxon_translation' => ['services', 'sylius.factory.taxon_translation', 'getSylius_Factory_TaxonTranslationService', true],
            'sylius.factory.zone' => ['services', 'Sylius\\Component\\Addressing\\Factory\\ZoneFactoryInterface', 'getZoneFactoryInterfaceService', true],
            'sylius.factory.zone_member' => ['services', 'sylius.factory.zone_member', 'getSylius_Factory_ZoneMemberService', true],
        ], [
            'sylius.factory.address' => '?',
            'sylius.factory.address_log_entry' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.adjustment' => '?',
            'sylius.factory.avatar_image' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.catalog_promotion' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.catalog_promotion_action' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.catalog_promotion_scope' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.catalog_promotion_translation' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.channel' => '?',
            'sylius.factory.channel_pricing' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.country' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.currency' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.customer' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.customer_group' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.exchange_rate' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.gateway_config' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.inventory_unit' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.locale' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.oauth_user' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.order' => '?',
            'sylius.factory.order_item' => '?',
            'sylius.factory.order_item_unit' => 'Sylius\\Component\\Order\\Factory\\OrderItemUnitFactory',
            'sylius.factory.order_sequence' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.payment' => '?',
            'sylius.factory.payment_method' => '?',
            'sylius.factory.payment_method_translation' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.payment_security_token' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product' => '?',
            'sylius.factory.product_association' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product_association_type' => 'Sylius\\Component\\Resource\\Factory\\TranslatableFactory',
            'sylius.factory.product_association_type_translation' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product_attribute_translation' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product_attribute_value' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product_image' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product_option' => 'Sylius\\Component\\Resource\\Factory\\TranslatableFactory',
            'sylius.factory.product_option_translation' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product_option_value' => 'Sylius\\Component\\Resource\\Factory\\TranslatableFactory',
            'sylius.factory.product_option_value_translation' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product_reviewer' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product_taxon' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product_translation' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.product_variant' => '?',
            'sylius.factory.product_variant_translation' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.promotion' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.promotion_action' => '?',
            'sylius.factory.promotion_coupon' => '?',
            'sylius.factory.promotion_rule' => '?',
            'sylius.factory.province' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.shipment' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.shipment_unit' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.shipping_category' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.shipping_method' => 'Sylius\\Component\\Resource\\Factory\\TranslatableFactory',
            'sylius.factory.shipping_method_rule' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.shipping_method_translation' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.shop_billing_data' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.tax_category' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.tax_rate' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.taxon' => '?',
            'sylius.factory.taxon_image' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.taxon_translation' => 'Sylius\\Component\\Resource\\Factory\\Factory',
            'sylius.factory.zone' => '?',
            'sylius.factory.zone_member' => 'Sylius\\Component\\Resource\\Factory\\Factory',
        ]), new \Sylius\Resource\Symfony\ExpressionLanguage\ArgumentParser(new \Symfony\Component\ExpressionLanguage\ExpressionLanguage(), new \Sylius\Resource\Symfony\ExpressionLanguage\VariablesCollection(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sylius.expression_language.variables.token'] ?? $container->load('getSylius_ExpressionLanguage_Variables_TokenService'));
            yield 1 => ($container->privates['sylius.expression_language.variables.request'] ?? $container->load('getSylius_ExpressionLanguage_Variables_RequestService'));
        }, 2))))), $a), $b), ($container->services['Sylius\\Resource\\Symfony\\Form\\Factory\\FormFactoryInterface'] ?? $container->load('getFormFactoryInterfaceService'))), ($container->services['validator'] ?? self::getValidatorService($container))), new \Sylius\Resource\State\Processor\WriteProcessor(new \Sylius\Resource\Symfony\Serializer\State\SerializeProcessor(new \Sylius\Resource\State\Processor\FlashProcessor(new \Sylius\Resource\State\Processor\RespondProcessor(new \Sylius\Resource\State\Responder(($container->privates['.service_locator.piEDfYt'] ?? $container->load('get_ServiceLocator_PiEDfYtService')))), $c), $b), new \Sylius\Resource\State\Processor\BulkAwareProcessor(new \Sylius\Resource\Symfony\EventDispatcher\State\DispatchPostWriteEventProcessor(new \Sylius\Resource\Symfony\EventDispatcher\State\DispatchPreWriteEventProcessor(new \Sylius\Resource\State\Processor(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Sylius\\Resource\\Doctrine\\Common\\State\\PersistProcessor' => ['privates', 'Sylius\\Resource\\Doctrine\\Common\\State\\PersistProcessor', 'getPersistProcessorService', true],
            'Sylius\\Resource\\Doctrine\\Common\\State\\RemoveProcessor' => ['privates', 'Sylius\\Resource\\Doctrine\\Common\\State\\RemoveProcessor', 'getRemoveProcessorService', true],
            'Sylius\\Resource\\StateMachine\\State\\ApplyStateMachineTransitionProcessor' => ['privates', 'Sylius\\Resource\\StateMachine\\State\\ApplyStateMachineTransitionProcessor', 'getApplyStateMachineTransitionProcessorService', true],
        ], [
            'Sylius\\Resource\\Doctrine\\Common\\State\\PersistProcessor' => 'Sylius\\Resource\\Doctrine\\Common\\State\\PersistProcessor',
            'Sylius\\Resource\\Doctrine\\Common\\State\\RemoveProcessor' => 'Sylius\\Resource\\Doctrine\\Common\\State\\RemoveProcessor',
            'Sylius\\Resource\\StateMachine\\State\\ApplyStateMachineTransitionProcessor' => 'Sylius\\Resource\\StateMachine\\State\\ApplyStateMachineTransitionProcessor',
        ])), $a, $d), $a, $d))));
    }
}
