<?php

namespace ContainerUsxYfYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyCustomerAccountHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\CommandHandler\Account\VerifyCustomerAccountHandler' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\CommandHandler\Account\VerifyCustomerAccountHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/CommandHandler/Account/VerifyCustomerAccountHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/calendar/src/Provider/DateTimeProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/calendar/src/Provider/Calendar.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\CommandHandler\\Account\\VerifyCustomerAccountHandler'] = new \Sylius\Bundle\ApiBundle\CommandHandler\Account\VerifyCustomerAccountHandler(($container->services['sylius.repository.shop_user'] ?? $container->load('getSylius_Repository_ShopUserService')), ($container->privates['Sylius\\Calendar\\Provider\\DateTimeProviderInterface'] ??= new \Sylius\Calendar\Provider\Calendar()));
    }
}
